// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_3_channel_pad_3_loop_for_channel_pad_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OutPadConv3_V_address0,
        OutPadConv3_V_ce0,
        OutPadConv3_V_we0,
        OutPadConv3_V_d0,
        max_pooling1d_5_V_address0,
        max_pooling1d_5_V_ce0,
        max_pooling1d_5_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] OutPadConv3_V_address0;
output   OutPadConv3_V_ce0;
output   OutPadConv3_V_we0;
output  [31:0] OutPadConv3_V_d0;
output  [11:0] max_pooling1d_5_V_address0;
output   max_pooling1d_5_V_ce0;
input  [31:0] max_pooling1d_5_V_q0;

reg ap_idle;
reg OutPadConv3_V_ce0;
reg OutPadConv3_V_we0;
reg max_pooling1d_5_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln118_fu_106_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln118_fu_130_p3;
reg   [4:0] select_ln118_reg_266;
reg   [4:0] select_ln118_reg_266_pp0_iter1_reg;
wire   [11:0] zext_ln118_fu_152_p1;
wire   [0:0] icmp_ln121_fu_183_p2;
reg   [0:0] icmp_ln121_reg_285;
reg   [0:0] icmp_ln121_reg_285_pp0_iter3_reg;
wire   [0:0] icmp_ln121_1_fu_188_p2;
reg   [0:0] icmp_ln121_1_reg_290;
reg   [0:0] icmp_ln121_1_reg_290_pp0_iter3_reg;
wire   [11:0] grp_fu_233_p3;
reg   [11:0] add_ln121_reg_300;
wire   [63:0] zext_ln121_1_fu_203_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln121_fu_211_p1;
reg   [4:0] n_fu_50;
wire   [4:0] add_ln120_fu_156_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_n_load;
reg   [7:0] c_fu_54;
wire   [7:0] select_ln118_1_fu_144_p3;
reg   [7:0] ap_sig_allocacmp_c_load;
reg   [11:0] indvar_flatten236_fu_58;
wire   [11:0] add_ln118_fu_112_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten236_load;
wire   [0:0] icmp_ln120_fu_124_p2;
wire   [7:0] add_ln118_1_fu_138_p2;
wire   [5:0] n_7_cast_fu_180_p1;
wire  signed [5:0] add_ln121_1_fu_193_p2;
wire  signed [11:0] zext_ln121_1_fu_203_p0;
wire   [11:0] grp_fu_224_p3;
wire   [0:0] or_ln121_fu_207_p2;
wire   [7:0] grp_fu_224_p0;
wire   [4:0] grp_fu_224_p1;
wire   [7:0] grp_fu_233_p0;
wire   [4:0] grp_fu_233_p1;
wire   [4:0] grp_fu_233_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] grp_fu_233_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_mac_muladd_8ns_5ns_6s_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mac_muladd_8ns_5ns_6s_12_4_1_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .din1(grp_fu_224_p1),
    .din2(add_ln121_1_fu_193_p2),
    .ce(1'b1),
    .dout(grp_fu_224_p3)
);

CNN_mac_muladd_8ns_5ns_5ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
mac_muladd_8ns_5ns_5ns_12_4_1_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_233_p0),
    .din1(grp_fu_233_p1),
    .din2(grp_fu_233_p2),
    .ce(1'b1),
    .dout(grp_fu_233_p3)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln118_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_54 <= select_ln118_1_fu_144_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_54 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln118_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten236_fu_58 <= add_ln118_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten236_fu_58 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln118_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_50 <= add_ln120_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_50 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln121_reg_300 <= grp_fu_233_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln118_reg_266_pp0_iter1_reg <= select_ln118_reg_266;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln121_1_reg_290 <= icmp_ln121_1_fu_188_p2;
        icmp_ln121_1_reg_290_pp0_iter3_reg <= icmp_ln121_1_reg_290;
        icmp_ln121_reg_285 <= icmp_ln121_fu_183_p2;
        icmp_ln121_reg_285_pp0_iter3_reg <= icmp_ln121_reg_285;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_fu_106_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln118_reg_266 <= select_ln118_fu_130_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        OutPadConv3_V_ce0 = 1'b1;
    end else begin
        OutPadConv3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        OutPadConv3_V_we0 = 1'b1;
    end else begin
        OutPadConv3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_106_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 8'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten236_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten236_load = indvar_flatten236_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_load = 5'd0;
    end else begin
        ap_sig_allocacmp_n_load = n_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        max_pooling1d_5_V_ce0 = 1'b1;
    end else begin
        max_pooling1d_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutPadConv3_V_address0 = zext_ln121_fu_211_p1;

assign OutPadConv3_V_d0 = ((or_ln121_fu_207_p2[0:0] == 1'b1) ? 32'd0 : max_pooling1d_5_V_q0);

assign add_ln118_1_fu_138_p2 = (ap_sig_allocacmp_c_load + 8'd1);

assign add_ln118_fu_112_p2 = (ap_sig_allocacmp_indvar_flatten236_load + 12'd1);

assign add_ln120_fu_156_p2 = (select_ln118_fu_130_p3 + 5'd1);

assign add_ln121_1_fu_193_p2 = ($signed(n_7_cast_fu_180_p1) + $signed(6'd63));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_224_p0 = zext_ln118_fu_152_p1;

assign grp_fu_224_p1 = 12'd21;

assign grp_fu_233_p0 = zext_ln118_fu_152_p1;

assign grp_fu_233_p1 = 12'd23;

assign grp_fu_233_p2 = grp_fu_233_p20;

assign grp_fu_233_p20 = select_ln118_reg_266_pp0_iter1_reg;

assign icmp_ln118_fu_106_p2 = ((ap_sig_allocacmp_indvar_flatten236_load == 12'd2944) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_124_p2 = ((ap_sig_allocacmp_n_load == 5'd23) ? 1'b1 : 1'b0);

assign icmp_ln121_1_fu_188_p2 = ((select_ln118_reg_266_pp0_iter1_reg > 5'd21) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_183_p2 = ((select_ln118_reg_266_pp0_iter1_reg == 5'd0) ? 1'b1 : 1'b0);

assign max_pooling1d_5_V_address0 = zext_ln121_1_fu_203_p1;

assign n_7_cast_fu_180_p1 = select_ln118_reg_266_pp0_iter1_reg;

assign or_ln121_fu_207_p2 = (icmp_ln121_reg_285_pp0_iter3_reg | icmp_ln121_1_reg_290_pp0_iter3_reg);

assign select_ln118_1_fu_144_p3 = ((icmp_ln120_fu_124_p2[0:0] == 1'b1) ? add_ln118_1_fu_138_p2 : ap_sig_allocacmp_c_load);

assign select_ln118_fu_130_p3 = ((icmp_ln120_fu_124_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_n_load);

assign zext_ln118_fu_152_p1 = select_ln118_1_fu_144_p3;

assign zext_ln121_1_fu_203_p0 = grp_fu_224_p3;

assign zext_ln121_1_fu_203_p1 = $unsigned(zext_ln121_1_fu_203_p0);

assign zext_ln121_fu_211_p1 = add_ln121_reg_300;

endmodule //CNN_CNN_Pipeline_loop_for_3_channel_pad_3_loop_for_channel_pad_3
