// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OutPadConv2_V_address0,
        OutPadConv2_V_ce0,
        OutPadConv2_V_we0,
        OutPadConv2_V_d0,
        max_pooling1d_4_V_address0,
        max_pooling1d_4_V_ce0,
        max_pooling1d_4_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] OutPadConv2_V_address0;
output   OutPadConv2_V_ce0;
output   OutPadConv2_V_we0;
output  [31:0] OutPadConv2_V_d0;
output  [11:0] max_pooling1d_4_V_address0;
output   max_pooling1d_4_V_ce0;
input  [31:0] max_pooling1d_4_V_q0;

reg ap_idle;
reg OutPadConv2_V_ce0;
reg OutPadConv2_V_we0;
reg max_pooling1d_4_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln81_fu_112_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln81_fu_136_p3;
reg   [5:0] select_ln81_reg_283;
reg   [5:0] select_ln81_reg_283_pp0_iter1_reg;
wire   [11:0] zext_ln81_fu_158_p1;
wire   [0:0] icmp_ln84_fu_172_p2;
reg   [0:0] icmp_ln84_reg_296;
reg   [0:0] icmp_ln84_reg_296_pp0_iter1_reg;
reg   [0:0] icmp_ln84_reg_296_pp0_iter2_reg;
reg   [0:0] icmp_ln84_reg_296_pp0_iter3_reg;
wire   [0:0] icmp_ln84_1_fu_205_p2;
reg   [0:0] icmp_ln84_1_reg_306;
reg   [0:0] icmp_ln84_1_reg_306_pp0_iter3_reg;
wire   [11:0] grp_fu_250_p3;
reg   [11:0] add_ln84_reg_316;
wire   [63:0] zext_ln84_1_fu_220_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln84_fu_228_p1;
reg   [5:0] n_fu_56;
wire   [5:0] add_ln83_fu_178_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_n_load;
reg   [6:0] c_fu_60;
wire   [6:0] select_ln81_1_fu_150_p3;
reg   [6:0] ap_sig_allocacmp_c_load;
reg   [11:0] indvar_flatten157_fu_64;
wire   [11:0] add_ln81_fu_118_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten157_load;
wire   [0:0] icmp_ln83_fu_130_p2;
wire   [6:0] add_ln81_1_fu_144_p2;
wire   [4:0] tmp_fu_162_p4;
wire   [6:0] n_5_cast_fu_202_p1;
wire  signed [6:0] add_ln84_1_fu_210_p2;
wire  signed [11:0] zext_ln84_1_fu_220_p0;
wire   [11:0] grp_fu_241_p3;
wire   [0:0] or_ln84_fu_224_p2;
wire   [6:0] grp_fu_241_p0;
wire   [5:0] grp_fu_241_p1;
wire   [6:0] grp_fu_250_p0;
wire   [5:0] grp_fu_250_p1;
wire   [5:0] grp_fu_250_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] grp_fu_250_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_mac_muladd_7ns_6ns_7s_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 12 ))
mac_muladd_7ns_6ns_7s_12_4_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_241_p0),
    .din1(grp_fu_241_p1),
    .din2(add_ln84_1_fu_210_p2),
    .ce(1'b1),
    .dout(grp_fu_241_p3)
);

CNN_mac_muladd_7ns_6ns_6ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mac_muladd_7ns_6ns_6ns_12_4_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_250_p0),
    .din1(grp_fu_250_p1),
    .din2(grp_fu_250_p2),
    .ce(1'b1),
    .dout(grp_fu_250_p3)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln81_fu_112_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_60 <= select_ln81_1_fu_150_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_60 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln81_fu_112_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten157_fu_64 <= add_ln81_fu_118_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten157_fu_64 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln81_fu_112_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_56 <= add_ln83_fu_178_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_56 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln84_reg_316 <= grp_fu_250_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln84_reg_296_pp0_iter1_reg <= icmp_ln84_reg_296;
        select_ln81_reg_283_pp0_iter1_reg <= select_ln81_reg_283;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln84_1_reg_306 <= icmp_ln84_1_fu_205_p2;
        icmp_ln84_1_reg_306_pp0_iter3_reg <= icmp_ln84_1_reg_306;
        icmp_ln84_reg_296_pp0_iter2_reg <= icmp_ln84_reg_296_pp0_iter1_reg;
        icmp_ln84_reg_296_pp0_iter3_reg <= icmp_ln84_reg_296_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln81_fu_112_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln84_reg_296 <= icmp_ln84_fu_172_p2;
        select_ln81_reg_283 <= select_ln81_fu_136_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        OutPadConv2_V_ce0 = 1'b1;
    end else begin
        OutPadConv2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        OutPadConv2_V_we0 = 1'b1;
    end else begin
        OutPadConv2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln81_fu_112_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 7'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten157_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten157_load = indvar_flatten157_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_load = 6'd0;
    end else begin
        ap_sig_allocacmp_n_load = n_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        max_pooling1d_4_V_ce0 = 1'b1;
    end else begin
        max_pooling1d_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutPadConv2_V_address0 = zext_ln84_fu_228_p1;

assign OutPadConv2_V_d0 = ((or_ln84_fu_224_p2[0:0] == 1'b1) ? 32'd0 : max_pooling1d_4_V_q0);

assign add_ln81_1_fu_144_p2 = (ap_sig_allocacmp_c_load + 7'd1);

assign add_ln81_fu_118_p2 = (ap_sig_allocacmp_indvar_flatten157_load + 12'd1);

assign add_ln83_fu_178_p2 = (select_ln81_fu_136_p3 + 6'd1);

assign add_ln84_1_fu_210_p2 = ($signed(n_5_cast_fu_202_p1) + $signed(7'd126));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_241_p0 = zext_ln81_fu_158_p1;

assign grp_fu_241_p1 = 12'd43;

assign grp_fu_250_p0 = zext_ln81_fu_158_p1;

assign grp_fu_250_p1 = 12'd47;

assign grp_fu_250_p2 = grp_fu_250_p20;

assign grp_fu_250_p20 = select_ln81_reg_283_pp0_iter1_reg;

assign icmp_ln81_fu_112_p2 = ((ap_sig_allocacmp_indvar_flatten157_load == 12'd3008) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_130_p2 = ((ap_sig_allocacmp_n_load == 6'd47) ? 1'b1 : 1'b0);

assign icmp_ln84_1_fu_205_p2 = ((select_ln81_reg_283_pp0_iter1_reg > 6'd44) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_172_p2 = ((tmp_fu_162_p4 == 5'd0) ? 1'b1 : 1'b0);

assign max_pooling1d_4_V_address0 = zext_ln84_1_fu_220_p1;

assign n_5_cast_fu_202_p1 = select_ln81_reg_283_pp0_iter1_reg;

assign or_ln84_fu_224_p2 = (icmp_ln84_reg_296_pp0_iter3_reg | icmp_ln84_1_reg_306_pp0_iter3_reg);

assign select_ln81_1_fu_150_p3 = ((icmp_ln83_fu_130_p2[0:0] == 1'b1) ? add_ln81_1_fu_144_p2 : ap_sig_allocacmp_c_load);

assign select_ln81_fu_136_p3 = ((icmp_ln83_fu_130_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_n_load);

assign tmp_fu_162_p4 = {{select_ln81_fu_136_p3[5:1]}};

assign zext_ln81_fu_158_p1 = select_ln81_1_fu_150_p3;

assign zext_ln84_1_fu_220_p0 = grp_fu_241_p3;

assign zext_ln84_1_fu_220_p1 = $unsigned(zext_ln84_1_fu_220_p0);

assign zext_ln84_fu_228_p1 = add_ln84_reg_316;

endmodule //CNN_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2
