// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_VITIS_LOOP_71_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        batch_normalization_8_V_address0,
        batch_normalization_8_V_ce0,
        batch_normalization_8_V_q0,
        batch_normalization_8_V_address1,
        batch_normalization_8_V_ce1,
        batch_normalization_8_V_q1,
        batch_normalization_8_V_address2,
        batch_normalization_8_V_ce2,
        batch_normalization_8_V_q2,
        batch_normalization_8_V_address3,
        batch_normalization_8_V_ce3,
        batch_normalization_8_V_q3,
        batch_normalization_8_V_address4,
        batch_normalization_8_V_ce4,
        batch_normalization_8_V_q4,
        batch_normalization_8_V_address5,
        batch_normalization_8_V_ce5,
        batch_normalization_8_V_q5,
        batch_normalization_8_V_address6,
        batch_normalization_8_V_ce6,
        batch_normalization_8_V_q6,
        batch_normalization_8_V_address7,
        batch_normalization_8_V_ce7,
        batch_normalization_8_V_q7,
        batch_normalization_8_V_address8,
        batch_normalization_8_V_ce8,
        batch_normalization_8_V_q8,
        batch_normalization_8_V_address9,
        batch_normalization_8_V_ce9,
        batch_normalization_8_V_q9,
        batch_normalization_8_V_address10,
        batch_normalization_8_V_ce10,
        batch_normalization_8_V_q10,
        global_average_pooling1d_1_V_address0,
        global_average_pooling1d_1_V_ce0,
        global_average_pooling1d_1_V_we0,
        global_average_pooling1d_1_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] batch_normalization_8_V_address0;
output   batch_normalization_8_V_ce0;
input  [31:0] batch_normalization_8_V_q0;
output  [7:0] batch_normalization_8_V_address1;
output   batch_normalization_8_V_ce1;
input  [31:0] batch_normalization_8_V_q1;
output  [7:0] batch_normalization_8_V_address2;
output   batch_normalization_8_V_ce2;
input  [31:0] batch_normalization_8_V_q2;
output  [7:0] batch_normalization_8_V_address3;
output   batch_normalization_8_V_ce3;
input  [31:0] batch_normalization_8_V_q3;
output  [7:0] batch_normalization_8_V_address4;
output   batch_normalization_8_V_ce4;
input  [31:0] batch_normalization_8_V_q4;
output  [7:0] batch_normalization_8_V_address5;
output   batch_normalization_8_V_ce5;
input  [31:0] batch_normalization_8_V_q5;
output  [7:0] batch_normalization_8_V_address6;
output   batch_normalization_8_V_ce6;
input  [31:0] batch_normalization_8_V_q6;
output  [7:0] batch_normalization_8_V_address7;
output   batch_normalization_8_V_ce7;
input  [31:0] batch_normalization_8_V_q7;
output  [7:0] batch_normalization_8_V_address8;
output   batch_normalization_8_V_ce8;
input  [31:0] batch_normalization_8_V_q8;
output  [7:0] batch_normalization_8_V_address9;
output   batch_normalization_8_V_ce9;
input  [31:0] batch_normalization_8_V_q9;
output  [7:0] batch_normalization_8_V_address10;
output   batch_normalization_8_V_ce10;
input  [31:0] batch_normalization_8_V_q10;
output  [3:0] global_average_pooling1d_1_V_address0;
output   global_average_pooling1d_1_V_ce0;
output   global_average_pooling1d_1_V_we0;
output  [31:0] global_average_pooling1d_1_V_d0;

reg ap_idle;
reg[7:0] batch_normalization_8_V_address0;
reg batch_normalization_8_V_ce0;
reg[7:0] batch_normalization_8_V_address1;
reg batch_normalization_8_V_ce1;
reg[7:0] batch_normalization_8_V_address2;
reg batch_normalization_8_V_ce2;
reg[7:0] batch_normalization_8_V_address3;
reg batch_normalization_8_V_ce3;
reg[7:0] batch_normalization_8_V_address4;
reg batch_normalization_8_V_ce4;
reg[7:0] batch_normalization_8_V_address5;
reg batch_normalization_8_V_ce5;
reg[7:0] batch_normalization_8_V_address6;
reg batch_normalization_8_V_ce6;
reg[7:0] batch_normalization_8_V_address7;
reg batch_normalization_8_V_ce7;
reg[7:0] batch_normalization_8_V_address8;
reg batch_normalization_8_V_ce8;
reg[7:0] batch_normalization_8_V_address9;
reg batch_normalization_8_V_ce9;
reg batch_normalization_8_V_ce10;
reg global_average_pooling1d_1_V_ce0;
reg global_average_pooling1d_1_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln71_reg_2119;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] i_reg_2114;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] i_reg_2114_pp0_iter1_reg;
wire   [0:0] icmp_ln71_fu_417_p2;
reg   [7:0] phi_mul_load_reg_2123;
wire   [0:0] tmp_fu_579_p3;
reg   [0:0] tmp_reg_2192;
wire    ap_block_pp0_stage1_11001;
wire   [27:0] tmp_62_fu_597_p4;
reg   [27:0] tmp_62_reg_2197;
wire   [27:0] sub_ln1303_1_fu_615_p2;
reg   [27:0] sub_ln1303_1_reg_2202;
wire   [0:0] grp_fu_324_p3;
reg   [0:0] tmp_63_reg_2207;
wire   [27:0] tmp_65_fu_647_p4;
reg   [27:0] tmp_65_reg_2212;
wire   [27:0] sub_ln1303_3_fu_665_p2;
reg   [27:0] sub_ln1303_3_reg_2217;
wire   [27:0] select_ln1303_5_fu_721_p3;
reg   [27:0] select_ln1303_5_reg_2222;
wire   [0:0] grp_fu_340_p3;
reg   [0:0] tmp_69_reg_2227;
wire   [27:0] tmp_71_fu_755_p4;
reg   [27:0] tmp_71_reg_2232;
wire   [27:0] sub_ln1303_7_fu_773_p2;
reg   [27:0] sub_ln1303_7_reg_2237;
wire   [0:0] grp_fu_348_p3;
reg   [0:0] tmp_72_reg_2242;
wire   [27:0] tmp_74_fu_805_p4;
reg   [27:0] tmp_74_reg_2247;
wire   [27:0] sub_ln1303_9_fu_823_p2;
reg   [27:0] sub_ln1303_9_reg_2252;
wire   [0:0] grp_fu_356_p3;
reg   [0:0] tmp_75_reg_2257;
wire   [27:0] tmp_77_fu_855_p4;
reg   [27:0] tmp_77_reg_2262;
wire   [27:0] sub_ln1303_11_fu_873_p2;
reg   [27:0] sub_ln1303_11_reg_2267;
wire   [0:0] grp_fu_364_p3;
reg   [0:0] tmp_78_reg_2272;
wire   [27:0] tmp_80_fu_905_p4;
reg   [27:0] tmp_80_reg_2277;
wire   [27:0] sub_ln1303_13_fu_923_p2;
reg   [27:0] sub_ln1303_13_reg_2282;
wire   [27:0] select_ln1303_15_fu_979_p3;
reg   [27:0] select_ln1303_15_reg_2287;
wire   [0:0] grp_fu_380_p3;
reg   [0:0] tmp_84_reg_2292;
wire   [27:0] tmp_86_fu_1013_p4;
reg   [27:0] tmp_86_reg_2297;
wire   [27:0] sub_ln1303_17_fu_1031_p2;
reg   [27:0] sub_ln1303_17_reg_2302;
wire   [0:0] grp_fu_388_p3;
reg   [0:0] tmp_87_reg_2307;
wire   [27:0] tmp_89_fu_1063_p4;
reg   [27:0] tmp_89_reg_2312;
wire   [27:0] sub_ln1303_19_fu_1081_p2;
reg   [27:0] sub_ln1303_19_reg_2317;
wire   [0:0] grp_fu_396_p3;
reg   [0:0] tmp_90_reg_2322;
wire   [27:0] tmp_92_fu_1113_p4;
reg   [27:0] tmp_92_reg_2327;
wire   [27:0] sub_ln1303_21_fu_1131_p2;
reg   [27:0] sub_ln1303_21_reg_2332;
reg   [0:0] tmp_93_reg_2387;
wire   [27:0] tmp_95_fu_1341_p4;
reg   [27:0] tmp_95_reg_2392;
wire   [27:0] sub_ln1303_23_fu_1359_p2;
reg   [27:0] sub_ln1303_23_reg_2397;
wire   [27:0] select_ln1303_25_fu_1415_p3;
reg   [27:0] select_ln1303_25_reg_2402;
reg   [0:0] tmp_99_reg_2407;
wire   [27:0] tmp_101_fu_1449_p4;
reg   [27:0] tmp_101_reg_2412;
wire   [27:0] sub_ln1303_27_fu_1467_p2;
reg   [27:0] sub_ln1303_27_reg_2417;
reg   [0:0] tmp_102_reg_2422;
wire   [27:0] tmp_104_fu_1499_p4;
reg   [27:0] tmp_104_reg_2427;
wire   [27:0] sub_ln1303_29_fu_1517_p2;
reg   [27:0] sub_ln1303_29_reg_2432;
reg   [0:0] tmp_105_reg_2437;
wire   [27:0] tmp_107_fu_1549_p4;
reg   [27:0] tmp_107_reg_2442;
wire   [27:0] sub_ln1303_31_fu_1567_p2;
reg   [27:0] sub_ln1303_31_reg_2447;
reg   [0:0] tmp_108_reg_2452;
wire   [27:0] tmp_110_fu_1599_p4;
reg   [27:0] tmp_110_reg_2457;
wire   [27:0] sub_ln1303_33_fu_1617_p2;
reg   [27:0] sub_ln1303_33_reg_2462;
wire   [0:0] grp_fu_372_p3;
reg   [0:0] tmp_111_reg_2467;
wire   [27:0] tmp_113_fu_1649_p4;
reg   [27:0] tmp_113_reg_2472;
wire   [27:0] sub_ln1303_35_fu_1667_p2;
reg   [27:0] sub_ln1303_35_reg_2477;
reg   [0:0] tmp_114_reg_2482;
wire   [27:0] tmp_116_fu_1699_p4;
reg   [27:0] tmp_116_reg_2487;
wire   [27:0] sub_ln1303_37_fu_1717_p2;
reg   [27:0] sub_ln1303_37_reg_2492;
reg   [0:0] tmp_117_reg_2497;
wire   [27:0] tmp_119_fu_1749_p4;
reg   [27:0] tmp_119_reg_2502;
wire   [27:0] sub_ln1303_39_fu_1767_p2;
reg   [27:0] sub_ln1303_39_reg_2507;
reg   [0:0] tmp_120_reg_2512;
wire   [27:0] tmp_122_fu_1799_p4;
reg   [27:0] tmp_122_reg_2517;
wire   [27:0] sub_ln1303_41_fu_1817_p2;
reg   [27:0] sub_ln1303_41_reg_2522;
wire   [30:0] add_ln813_28_fu_1895_p2;
reg   [30:0] add_ln813_28_reg_2527;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln74_fu_438_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln74_1_fu_449_p1;
wire   [63:0] zext_ln74_2_fu_460_p1;
wire   [63:0] zext_ln74_3_fu_471_p1;
wire   [63:0] zext_ln74_4_fu_482_p1;
wire   [63:0] zext_ln74_5_fu_493_p1;
wire   [63:0] zext_ln74_6_fu_504_p1;
wire   [63:0] zext_ln74_7_fu_515_p1;
wire   [63:0] zext_ln74_8_fu_526_p1;
wire   [63:0] zext_ln74_9_fu_537_p1;
wire   [63:0] zext_ln74_10_fu_548_p1;
wire   [63:0] zext_ln74_11_fu_1142_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln74_12_fu_1152_p1;
wire   [63:0] zext_ln74_13_fu_1162_p1;
wire   [63:0] zext_ln74_14_fu_1172_p1;
wire   [63:0] zext_ln74_15_fu_1182_p1;
wire   [63:0] zext_ln74_16_fu_1192_p1;
wire   [63:0] zext_ln74_17_fu_1202_p1;
wire   [63:0] zext_ln74_18_fu_1212_p1;
wire   [63:0] zext_ln74_19_fu_1222_p1;
wire   [63:0] zext_ln74_20_fu_1232_p1;
wire   [63:0] i_6_cast106_fu_1901_p1;
reg   [7:0] phi_mul_fu_90;
wire   [7:0] next_mul_fu_432_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_phi_mul_load;
reg   [3:0] hs_fu_94;
wire   [3:0] add_ln71_fu_423_p2;
reg   [3:0] ap_sig_allocacmp_i;
wire  signed [31:0] grp_fu_324_p1;
wire  signed [31:0] grp_fu_332_p1;
wire  signed [31:0] grp_fu_340_p1;
wire  signed [31:0] grp_fu_348_p1;
wire  signed [31:0] grp_fu_356_p1;
wire  signed [31:0] grp_fu_364_p1;
wire  signed [31:0] grp_fu_372_p1;
wire  signed [31:0] grp_fu_380_p1;
wire  signed [31:0] grp_fu_388_p1;
wire  signed [31:0] grp_fu_396_p1;
wire   [7:0] add_ln74_fu_443_p2;
wire   [7:0] add_ln74_1_fu_454_p2;
wire   [7:0] add_ln74_2_fu_465_p2;
wire   [7:0] add_ln74_3_fu_476_p2;
wire   [7:0] add_ln74_4_fu_487_p2;
wire   [7:0] add_ln74_5_fu_498_p2;
wire   [7:0] add_ln74_6_fu_509_p2;
wire   [7:0] add_ln74_7_fu_520_p2;
wire   [7:0] add_ln74_8_fu_531_p2;
wire   [7:0] add_ln74_9_fu_542_p2;
wire   [33:0] mul_ln1303_fu_567_p1;
wire   [64:0] mul_ln1303_fu_567_p2;
wire  signed [31:0] tmp_fu_579_p1;
wire   [64:0] sub_ln1303_fu_573_p2;
wire   [27:0] tmp_61_fu_587_p4;
wire   [27:0] select_ln1303_fu_607_p3;
wire   [33:0] mul_ln1303_1_fu_625_p1;
wire   [64:0] mul_ln1303_1_fu_625_p2;
wire   [64:0] sub_ln1303_2_fu_631_p2;
wire   [27:0] tmp_64_fu_637_p4;
wire   [27:0] select_ln1303_2_fu_657_p3;
wire   [33:0] mul_ln1303_2_fu_675_p1;
wire   [64:0] mul_ln1303_2_fu_675_p2;
wire   [64:0] sub_ln1303_4_fu_681_p2;
wire   [0:0] grp_fu_332_p3;
wire   [27:0] tmp_67_fu_687_p4;
wire   [27:0] tmp_68_fu_697_p4;
wire   [27:0] select_ln1303_4_fu_707_p3;
wire   [27:0] sub_ln1303_5_fu_715_p2;
wire   [33:0] mul_ln1303_3_fu_733_p1;
wire   [64:0] mul_ln1303_3_fu_733_p2;
wire   [64:0] sub_ln1303_6_fu_739_p2;
wire   [27:0] tmp_70_fu_745_p4;
wire   [27:0] select_ln1303_6_fu_765_p3;
wire   [33:0] mul_ln1303_4_fu_783_p1;
wire   [64:0] mul_ln1303_4_fu_783_p2;
wire   [64:0] sub_ln1303_8_fu_789_p2;
wire   [27:0] tmp_73_fu_795_p4;
wire   [27:0] select_ln1303_8_fu_815_p3;
wire   [33:0] mul_ln1303_5_fu_833_p1;
wire   [64:0] mul_ln1303_5_fu_833_p2;
wire   [64:0] sub_ln1303_10_fu_839_p2;
wire   [27:0] tmp_76_fu_845_p4;
wire   [27:0] select_ln1303_10_fu_865_p3;
wire   [33:0] mul_ln1303_6_fu_883_p1;
wire   [64:0] mul_ln1303_6_fu_883_p2;
wire   [64:0] sub_ln1303_12_fu_889_p2;
wire   [27:0] tmp_79_fu_895_p4;
wire   [27:0] select_ln1303_12_fu_915_p3;
wire   [33:0] mul_ln1303_7_fu_933_p1;
wire   [64:0] mul_ln1303_7_fu_933_p2;
wire   [64:0] sub_ln1303_14_fu_939_p2;
wire   [27:0] tmp_82_fu_945_p4;
wire   [27:0] tmp_83_fu_955_p4;
wire   [27:0] select_ln1303_14_fu_965_p3;
wire   [27:0] sub_ln1303_15_fu_973_p2;
wire   [33:0] mul_ln1303_8_fu_991_p1;
wire   [64:0] mul_ln1303_8_fu_991_p2;
wire   [64:0] sub_ln1303_16_fu_997_p2;
wire   [27:0] tmp_85_fu_1003_p4;
wire   [27:0] select_ln1303_16_fu_1023_p3;
wire   [33:0] mul_ln1303_9_fu_1041_p1;
wire   [64:0] mul_ln1303_9_fu_1041_p2;
wire   [64:0] sub_ln1303_18_fu_1047_p2;
wire   [27:0] tmp_88_fu_1053_p4;
wire   [27:0] select_ln1303_18_fu_1073_p3;
wire   [33:0] mul_ln1303_10_fu_1091_p1;
wire   [64:0] mul_ln1303_10_fu_1091_p2;
wire   [64:0] sub_ln1303_20_fu_1097_p2;
wire   [27:0] tmp_91_fu_1103_p4;
wire   [27:0] select_ln1303_20_fu_1123_p3;
wire   [7:0] add_ln74_10_fu_1137_p2;
wire   [7:0] add_ln74_11_fu_1147_p2;
wire   [7:0] add_ln74_12_fu_1157_p2;
wire   [7:0] add_ln74_13_fu_1167_p2;
wire   [7:0] add_ln74_14_fu_1177_p2;
wire   [7:0] add_ln74_15_fu_1187_p2;
wire   [7:0] add_ln74_16_fu_1197_p2;
wire   [7:0] add_ln74_17_fu_1207_p2;
wire   [7:0] add_ln74_18_fu_1217_p2;
wire   [7:0] add_ln74_19_fu_1227_p2;
wire   [27:0] select_ln1303_1_fu_1237_p3;
wire   [27:0] select_ln1303_3_fu_1246_p3;
wire   [27:0] select_ln1303_7_fu_1258_p3;
wire   [27:0] select_ln1303_9_fu_1267_p3;
wire   [27:0] select_ln1303_11_fu_1276_p3;
wire   [27:0] select_ln1303_13_fu_1285_p3;
wire   [27:0] select_ln1303_17_fu_1297_p3;
wire   [27:0] select_ln1303_19_fu_1306_p3;
wire   [33:0] mul_ln1303_11_fu_1319_p1;
wire   [64:0] mul_ln1303_11_fu_1319_p2;
wire   [64:0] sub_ln1303_22_fu_1325_p2;
wire   [27:0] tmp_94_fu_1331_p4;
wire   [27:0] select_ln1303_22_fu_1351_p3;
wire   [33:0] mul_ln1303_12_fu_1369_p1;
wire   [64:0] mul_ln1303_12_fu_1369_p2;
wire   [64:0] sub_ln1303_24_fu_1375_p2;
wire   [27:0] tmp_97_fu_1381_p4;
wire   [27:0] tmp_98_fu_1391_p4;
wire   [27:0] select_ln1303_24_fu_1401_p3;
wire   [27:0] sub_ln1303_25_fu_1409_p2;
wire   [33:0] mul_ln1303_13_fu_1427_p1;
wire   [64:0] mul_ln1303_13_fu_1427_p2;
wire   [64:0] sub_ln1303_26_fu_1433_p2;
wire   [27:0] tmp_100_fu_1439_p4;
wire   [27:0] select_ln1303_26_fu_1459_p3;
wire   [33:0] mul_ln1303_14_fu_1477_p1;
wire   [64:0] mul_ln1303_14_fu_1477_p2;
wire   [64:0] sub_ln1303_28_fu_1483_p2;
wire   [27:0] tmp_103_fu_1489_p4;
wire   [27:0] select_ln1303_28_fu_1509_p3;
wire   [33:0] mul_ln1303_15_fu_1527_p1;
wire   [64:0] mul_ln1303_15_fu_1527_p2;
wire   [64:0] sub_ln1303_30_fu_1533_p2;
wire   [27:0] tmp_106_fu_1539_p4;
wire   [27:0] select_ln1303_30_fu_1559_p3;
wire   [33:0] mul_ln1303_16_fu_1577_p1;
wire   [64:0] mul_ln1303_16_fu_1577_p2;
wire   [64:0] sub_ln1303_32_fu_1583_p2;
wire   [27:0] tmp_109_fu_1589_p4;
wire   [27:0] select_ln1303_32_fu_1609_p3;
wire   [33:0] mul_ln1303_17_fu_1627_p1;
wire   [64:0] mul_ln1303_17_fu_1627_p2;
wire   [64:0] sub_ln1303_34_fu_1633_p2;
wire   [27:0] tmp_112_fu_1639_p4;
wire   [27:0] select_ln1303_34_fu_1659_p3;
wire   [33:0] mul_ln1303_18_fu_1677_p1;
wire   [64:0] mul_ln1303_18_fu_1677_p2;
wire   [64:0] sub_ln1303_36_fu_1683_p2;
wire   [27:0] tmp_115_fu_1689_p4;
wire   [27:0] select_ln1303_36_fu_1709_p3;
wire   [33:0] mul_ln1303_19_fu_1727_p1;
wire   [64:0] mul_ln1303_19_fu_1727_p2;
wire   [64:0] sub_ln1303_38_fu_1733_p2;
wire   [27:0] tmp_118_fu_1739_p4;
wire   [27:0] select_ln1303_38_fu_1759_p3;
wire   [33:0] mul_ln1303_20_fu_1777_p1;
wire   [64:0] mul_ln1303_20_fu_1777_p2;
wire   [64:0] sub_ln1303_40_fu_1783_p2;
wire   [27:0] tmp_121_fu_1789_p4;
wire   [27:0] select_ln1303_40_fu_1809_p3;
wire  signed [28:0] sext_ln74_1_fu_1251_p1;
wire  signed [28:0] sext_ln74_fu_1242_p1;
wire   [28:0] add_ln813_fu_1823_p2;
wire  signed [28:0] sext_ln74_3_fu_1263_p1;
wire  signed [28:0] sext_ln74_4_fu_1272_p1;
wire   [28:0] add_ln813_21_fu_1833_p2;
wire  signed [29:0] sext_ln813_2_fu_1839_p1;
wire  signed [29:0] sext_ln74_2_fu_1255_p1;
wire   [29:0] add_ln813_22_fu_1843_p2;
wire  signed [29:0] sext_ln813_1_fu_1829_p1;
wire   [29:0] add_ln813_23_fu_1849_p2;
wire  signed [28:0] sext_ln74_5_fu_1281_p1;
wire  signed [28:0] sext_ln74_6_fu_1290_p1;
wire   [28:0] add_ln813_24_fu_1859_p2;
wire  signed [28:0] sext_ln74_8_fu_1302_p1;
wire  signed [28:0] sext_ln74_9_fu_1311_p1;
wire   [28:0] add_ln813_25_fu_1869_p2;
wire  signed [29:0] sext_ln813_5_fu_1875_p1;
wire  signed [29:0] sext_ln74_7_fu_1294_p1;
wire   [29:0] add_ln813_26_fu_1879_p2;
wire  signed [29:0] sext_ln813_4_fu_1865_p1;
wire   [29:0] add_ln813_27_fu_1885_p2;
wire  signed [30:0] sext_ln813_6_fu_1891_p1;
wire  signed [30:0] sext_ln813_3_fu_1855_p1;
wire   [27:0] select_ln1303_21_fu_1905_p3;
wire   [27:0] select_ln1303_23_fu_1914_p3;
wire   [27:0] select_ln1303_27_fu_1926_p3;
wire   [27:0] select_ln1303_29_fu_1935_p3;
wire   [27:0] select_ln1303_31_fu_1944_p3;
wire   [27:0] select_ln1303_33_fu_1953_p3;
wire   [27:0] select_ln1303_35_fu_1962_p3;
wire   [27:0] select_ln1303_37_fu_1971_p3;
wire   [27:0] select_ln1303_39_fu_1980_p3;
wire   [27:0] select_ln1303_41_fu_1989_p3;
wire  signed [28:0] sext_ln74_10_fu_1910_p1;
wire  signed [28:0] sext_ln74_11_fu_1919_p1;
wire   [28:0] add_ln813_29_fu_2001_p2;
wire  signed [28:0] sext_ln74_13_fu_1931_p1;
wire  signed [28:0] sext_ln74_14_fu_1940_p1;
wire   [28:0] add_ln813_30_fu_2011_p2;
wire  signed [29:0] sext_ln813_9_fu_2017_p1;
wire  signed [29:0] sext_ln74_12_fu_1923_p1;
wire   [29:0] add_ln813_32_fu_2021_p2;
wire  signed [29:0] sext_ln813_8_fu_2007_p1;
wire   [29:0] add_ln813_33_fu_2027_p2;
wire  signed [28:0] sext_ln74_16_fu_1958_p1;
wire  signed [28:0] sext_ln74_17_fu_1967_p1;
wire   [28:0] add_ln813_34_fu_2037_p2;
wire  signed [29:0] sext_ln813_11_fu_2043_p1;
wire  signed [29:0] sext_ln74_15_fu_1949_p1;
wire   [29:0] add_ln813_35_fu_2047_p2;
wire  signed [28:0] sext_ln74_19_fu_1985_p1;
wire  signed [28:0] sext_ln813_fu_1994_p1;
wire   [28:0] add_ln813_36_fu_2057_p2;
wire  signed [29:0] sext_ln813_13_fu_2063_p1;
wire  signed [29:0] sext_ln74_18_fu_1976_p1;
wire   [29:0] add_ln813_37_fu_2067_p2;
wire  signed [30:0] sext_ln813_14_fu_2073_p1;
wire  signed [30:0] sext_ln813_12_fu_2053_p1;
wire   [30:0] add_ln813_38_fu_2077_p2;
wire  signed [31:0] sext_ln813_15_fu_2083_p1;
wire  signed [31:0] sext_ln813_10_fu_2033_p1;
wire   [31:0] add_ln813_39_fu_2087_p2;
wire  signed [31:0] sext_ln813_7_fu_1998_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U111(
    .din0(batch_normalization_8_V_q10),
    .din1(mul_ln1303_fu_567_p1),
    .dout(mul_ln1303_fu_567_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U112(
    .din0(batch_normalization_8_V_q9),
    .din1(mul_ln1303_1_fu_625_p1),
    .dout(mul_ln1303_1_fu_625_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U113(
    .din0(batch_normalization_8_V_q8),
    .din1(mul_ln1303_2_fu_675_p1),
    .dout(mul_ln1303_2_fu_675_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U114(
    .din0(batch_normalization_8_V_q7),
    .din1(mul_ln1303_3_fu_733_p1),
    .dout(mul_ln1303_3_fu_733_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U115(
    .din0(batch_normalization_8_V_q6),
    .din1(mul_ln1303_4_fu_783_p1),
    .dout(mul_ln1303_4_fu_783_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U116(
    .din0(batch_normalization_8_V_q5),
    .din1(mul_ln1303_5_fu_833_p1),
    .dout(mul_ln1303_5_fu_833_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U117(
    .din0(batch_normalization_8_V_q4),
    .din1(mul_ln1303_6_fu_883_p1),
    .dout(mul_ln1303_6_fu_883_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U118(
    .din0(batch_normalization_8_V_q3),
    .din1(mul_ln1303_7_fu_933_p1),
    .dout(mul_ln1303_7_fu_933_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U119(
    .din0(batch_normalization_8_V_q2),
    .din1(mul_ln1303_8_fu_991_p1),
    .dout(mul_ln1303_8_fu_991_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U120(
    .din0(batch_normalization_8_V_q1),
    .din1(mul_ln1303_9_fu_1041_p1),
    .dout(mul_ln1303_9_fu_1041_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U121(
    .din0(batch_normalization_8_V_q0),
    .din1(mul_ln1303_10_fu_1091_p1),
    .dout(mul_ln1303_10_fu_1091_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U122(
    .din0(batch_normalization_8_V_q9),
    .din1(mul_ln1303_11_fu_1319_p1),
    .dout(mul_ln1303_11_fu_1319_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U123(
    .din0(batch_normalization_8_V_q8),
    .din1(mul_ln1303_12_fu_1369_p1),
    .dout(mul_ln1303_12_fu_1369_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U124(
    .din0(batch_normalization_8_V_q7),
    .din1(mul_ln1303_13_fu_1427_p1),
    .dout(mul_ln1303_13_fu_1427_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U125(
    .din0(batch_normalization_8_V_q6),
    .din1(mul_ln1303_14_fu_1477_p1),
    .dout(mul_ln1303_14_fu_1477_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U126(
    .din0(batch_normalization_8_V_q5),
    .din1(mul_ln1303_15_fu_1527_p1),
    .dout(mul_ln1303_15_fu_1527_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U127(
    .din0(batch_normalization_8_V_q4),
    .din1(mul_ln1303_16_fu_1577_p1),
    .dout(mul_ln1303_16_fu_1577_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U128(
    .din0(batch_normalization_8_V_q3),
    .din1(mul_ln1303_17_fu_1627_p1),
    .dout(mul_ln1303_17_fu_1627_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U129(
    .din0(batch_normalization_8_V_q2),
    .din1(mul_ln1303_18_fu_1677_p1),
    .dout(mul_ln1303_18_fu_1677_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U130(
    .din0(batch_normalization_8_V_q1),
    .din1(mul_ln1303_19_fu_1727_p1),
    .dout(mul_ln1303_19_fu_1727_p2)
);

CNN_mul_32s_34ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 65 ))
mul_32s_34ns_65_1_1_U131(
    .din0(batch_normalization_8_V_q0),
    .din1(mul_ln1303_20_fu_1777_p1),
    .dout(mul_ln1303_20_fu_1777_p2)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln71_fu_417_p2 == 1'd0))) begin
            hs_fu_94 <= add_ln71_fu_423_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            hs_fu_94 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln71_fu_417_p2 == 1'd0))) begin
            phi_mul_fu_90 <= next_mul_fu_432_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_90 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln813_28_reg_2527 <= add_ln813_28_fu_1895_p2;
        i_reg_2114 <= ap_sig_allocacmp_i;
        i_reg_2114_pp0_iter1_reg <= i_reg_2114;
        icmp_ln71_reg_2119 <= icmp_ln71_fu_417_p2;
        select_ln1303_25_reg_2402 <= select_ln1303_25_fu_1415_p3;
        sub_ln1303_23_reg_2397 <= sub_ln1303_23_fu_1359_p2;
        sub_ln1303_27_reg_2417 <= sub_ln1303_27_fu_1467_p2;
        sub_ln1303_29_reg_2432 <= sub_ln1303_29_fu_1517_p2;
        sub_ln1303_31_reg_2447 <= sub_ln1303_31_fu_1567_p2;
        sub_ln1303_33_reg_2462 <= sub_ln1303_33_fu_1617_p2;
        sub_ln1303_35_reg_2477 <= sub_ln1303_35_fu_1667_p2;
        sub_ln1303_37_reg_2492 <= sub_ln1303_37_fu_1717_p2;
        sub_ln1303_39_reg_2507 <= sub_ln1303_39_fu_1767_p2;
        sub_ln1303_41_reg_2522 <= sub_ln1303_41_fu_1817_p2;
        tmp_101_reg_2412 <= {{mul_ln1303_13_fu_1427_p2[64:37]}};
        tmp_104_reg_2427 <= {{mul_ln1303_14_fu_1477_p2[64:37]}};
        tmp_107_reg_2442 <= {{mul_ln1303_15_fu_1527_p2[64:37]}};
        tmp_110_reg_2457 <= {{mul_ln1303_16_fu_1577_p2[64:37]}};
        tmp_113_reg_2472 <= {{mul_ln1303_17_fu_1627_p2[64:37]}};
        tmp_116_reg_2487 <= {{mul_ln1303_18_fu_1677_p2[64:37]}};
        tmp_119_reg_2502 <= {{mul_ln1303_19_fu_1727_p2[64:37]}};
        tmp_122_reg_2517 <= {{mul_ln1303_20_fu_1777_p2[64:37]}};
        tmp_95_reg_2392 <= {{mul_ln1303_11_fu_1319_p2[64:37]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln71_fu_417_p2 == 1'd0))) begin
        phi_mul_load_reg_2123 <= ap_sig_allocacmp_phi_mul_load;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln71_reg_2119 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        select_ln1303_15_reg_2287 <= select_ln1303_15_fu_979_p3;
        select_ln1303_5_reg_2222 <= select_ln1303_5_fu_721_p3;
        sub_ln1303_11_reg_2267 <= sub_ln1303_11_fu_873_p2;
        sub_ln1303_13_reg_2282 <= sub_ln1303_13_fu_923_p2;
        sub_ln1303_17_reg_2302 <= sub_ln1303_17_fu_1031_p2;
        sub_ln1303_19_reg_2317 <= sub_ln1303_19_fu_1081_p2;
        sub_ln1303_1_reg_2202 <= sub_ln1303_1_fu_615_p2;
        sub_ln1303_21_reg_2332 <= sub_ln1303_21_fu_1131_p2;
        sub_ln1303_3_reg_2217 <= sub_ln1303_3_fu_665_p2;
        sub_ln1303_7_reg_2237 <= sub_ln1303_7_fu_773_p2;
        sub_ln1303_9_reg_2252 <= sub_ln1303_9_fu_823_p2;
        tmp_62_reg_2197 <= {{mul_ln1303_fu_567_p2[64:37]}};
        tmp_65_reg_2212 <= {{mul_ln1303_1_fu_625_p2[64:37]}};
        tmp_71_reg_2232 <= {{mul_ln1303_3_fu_733_p2[64:37]}};
        tmp_74_reg_2247 <= {{mul_ln1303_4_fu_783_p2[64:37]}};
        tmp_77_reg_2262 <= {{mul_ln1303_5_fu_833_p2[64:37]}};
        tmp_80_reg_2277 <= {{mul_ln1303_6_fu_883_p2[64:37]}};
        tmp_86_reg_2297 <= {{mul_ln1303_8_fu_991_p2[64:37]}};
        tmp_89_reg_2312 <= {{mul_ln1303_9_fu_1041_p2[64:37]}};
        tmp_92_reg_2327 <= {{mul_ln1303_10_fu_1091_p2[64:37]}};
        tmp_reg_2192 <= tmp_fu_579_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_102_reg_2422 <= grp_fu_348_p1[32'd31];
        tmp_105_reg_2437 <= grp_fu_356_p1[32'd31];
        tmp_108_reg_2452 <= grp_fu_364_p1[32'd31];
        tmp_111_reg_2467 <= grp_fu_372_p1[32'd31];
        tmp_114_reg_2482 <= grp_fu_380_p1[32'd31];
        tmp_117_reg_2497 <= grp_fu_388_p1[32'd31];
        tmp_120_reg_2512 <= grp_fu_396_p1[32'd31];
        tmp_93_reg_2387 <= grp_fu_324_p1[32'd31];
        tmp_99_reg_2407 <= grp_fu_340_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln71_reg_2119 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_63_reg_2207 <= grp_fu_324_p1[32'd31];
        tmp_69_reg_2227 <= grp_fu_340_p1[32'd31];
        tmp_72_reg_2242 <= grp_fu_348_p1[32'd31];
        tmp_75_reg_2257 <= grp_fu_356_p1[32'd31];
        tmp_78_reg_2272 <= grp_fu_364_p1[32'd31];
        tmp_84_reg_2292 <= grp_fu_380_p1[32'd31];
        tmp_87_reg_2307 <= grp_fu_388_p1[32'd31];
        tmp_90_reg_2322 <= grp_fu_396_p1[32'd31];
    end
end

always @ (*) begin
    if (((icmp_ln71_reg_2119 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = hs_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_mul_load = 8'd0;
    end else begin
        ap_sig_allocacmp_phi_mul_load = phi_mul_fu_90;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address0 = zext_ln74_20_fu_1232_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address0 = zext_ln74_10_fu_548_p1;
        end else begin
            batch_normalization_8_V_address0 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address1 = zext_ln74_19_fu_1222_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address1 = zext_ln74_9_fu_537_p1;
        end else begin
            batch_normalization_8_V_address1 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address2 = zext_ln74_18_fu_1212_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address2 = zext_ln74_8_fu_526_p1;
        end else begin
            batch_normalization_8_V_address2 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address2 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address3 = zext_ln74_17_fu_1202_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address3 = zext_ln74_7_fu_515_p1;
        end else begin
            batch_normalization_8_V_address3 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address3 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address4 = zext_ln74_16_fu_1192_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address4 = zext_ln74_6_fu_504_p1;
        end else begin
            batch_normalization_8_V_address4 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address4 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address5 = zext_ln74_15_fu_1182_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address5 = zext_ln74_5_fu_493_p1;
        end else begin
            batch_normalization_8_V_address5 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address5 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address6 = zext_ln74_14_fu_1172_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address6 = zext_ln74_4_fu_482_p1;
        end else begin
            batch_normalization_8_V_address6 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address6 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address7 = zext_ln74_13_fu_1162_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address7 = zext_ln74_3_fu_471_p1;
        end else begin
            batch_normalization_8_V_address7 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address7 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address8 = zext_ln74_12_fu_1152_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address8 = zext_ln74_2_fu_460_p1;
        end else begin
            batch_normalization_8_V_address8 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address8 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            batch_normalization_8_V_address9 = zext_ln74_11_fu_1142_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            batch_normalization_8_V_address9 = zext_ln74_1_fu_449_p1;
        end else begin
            batch_normalization_8_V_address9 = 'bx;
        end
    end else begin
        batch_normalization_8_V_address9 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce0 = 1'b1;
    end else begin
        batch_normalization_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce1 = 1'b1;
    end else begin
        batch_normalization_8_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        batch_normalization_8_V_ce10 = 1'b1;
    end else begin
        batch_normalization_8_V_ce10 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce2 = 1'b1;
    end else begin
        batch_normalization_8_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce3 = 1'b1;
    end else begin
        batch_normalization_8_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce4 = 1'b1;
    end else begin
        batch_normalization_8_V_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce5 = 1'b1;
    end else begin
        batch_normalization_8_V_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce6 = 1'b1;
    end else begin
        batch_normalization_8_V_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce7 = 1'b1;
    end else begin
        batch_normalization_8_V_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce8 = 1'b1;
    end else begin
        batch_normalization_8_V_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        batch_normalization_8_V_ce9 = 1'b1;
    end else begin
        batch_normalization_8_V_ce9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        global_average_pooling1d_1_V_ce0 = 1'b1;
    end else begin
        global_average_pooling1d_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        global_average_pooling1d_1_V_we0 = 1'b1;
    end else begin
        global_average_pooling1d_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln71_fu_423_p2 = (ap_sig_allocacmp_i + 4'd1);

assign add_ln74_10_fu_1137_p2 = (phi_mul_load_reg_2123 + 8'd11);

assign add_ln74_11_fu_1147_p2 = (phi_mul_load_reg_2123 + 8'd12);

assign add_ln74_12_fu_1157_p2 = (phi_mul_load_reg_2123 + 8'd13);

assign add_ln74_13_fu_1167_p2 = (phi_mul_load_reg_2123 + 8'd14);

assign add_ln74_14_fu_1177_p2 = (phi_mul_load_reg_2123 + 8'd15);

assign add_ln74_15_fu_1187_p2 = (phi_mul_load_reg_2123 + 8'd16);

assign add_ln74_16_fu_1197_p2 = (phi_mul_load_reg_2123 + 8'd17);

assign add_ln74_17_fu_1207_p2 = (phi_mul_load_reg_2123 + 8'd18);

assign add_ln74_18_fu_1217_p2 = (phi_mul_load_reg_2123 + 8'd19);

assign add_ln74_19_fu_1227_p2 = (phi_mul_load_reg_2123 + 8'd20);

assign add_ln74_1_fu_454_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd2);

assign add_ln74_2_fu_465_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd3);

assign add_ln74_3_fu_476_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd4);

assign add_ln74_4_fu_487_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd5);

assign add_ln74_5_fu_498_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd6);

assign add_ln74_6_fu_509_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd7);

assign add_ln74_7_fu_520_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd8);

assign add_ln74_8_fu_531_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd9);

assign add_ln74_9_fu_542_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd10);

assign add_ln74_fu_443_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd1);

assign add_ln813_21_fu_1833_p2 = ($signed(sext_ln74_3_fu_1263_p1) + $signed(sext_ln74_4_fu_1272_p1));

assign add_ln813_22_fu_1843_p2 = ($signed(sext_ln813_2_fu_1839_p1) + $signed(sext_ln74_2_fu_1255_p1));

assign add_ln813_23_fu_1849_p2 = ($signed(add_ln813_22_fu_1843_p2) + $signed(sext_ln813_1_fu_1829_p1));

assign add_ln813_24_fu_1859_p2 = ($signed(sext_ln74_5_fu_1281_p1) + $signed(sext_ln74_6_fu_1290_p1));

assign add_ln813_25_fu_1869_p2 = ($signed(sext_ln74_8_fu_1302_p1) + $signed(sext_ln74_9_fu_1311_p1));

assign add_ln813_26_fu_1879_p2 = ($signed(sext_ln813_5_fu_1875_p1) + $signed(sext_ln74_7_fu_1294_p1));

assign add_ln813_27_fu_1885_p2 = ($signed(add_ln813_26_fu_1879_p2) + $signed(sext_ln813_4_fu_1865_p1));

assign add_ln813_28_fu_1895_p2 = ($signed(sext_ln813_6_fu_1891_p1) + $signed(sext_ln813_3_fu_1855_p1));

assign add_ln813_29_fu_2001_p2 = ($signed(sext_ln74_10_fu_1910_p1) + $signed(sext_ln74_11_fu_1919_p1));

assign add_ln813_30_fu_2011_p2 = ($signed(sext_ln74_13_fu_1931_p1) + $signed(sext_ln74_14_fu_1940_p1));

assign add_ln813_32_fu_2021_p2 = ($signed(sext_ln813_9_fu_2017_p1) + $signed(sext_ln74_12_fu_1923_p1));

assign add_ln813_33_fu_2027_p2 = ($signed(add_ln813_32_fu_2021_p2) + $signed(sext_ln813_8_fu_2007_p1));

assign add_ln813_34_fu_2037_p2 = ($signed(sext_ln74_16_fu_1958_p1) + $signed(sext_ln74_17_fu_1967_p1));

assign add_ln813_35_fu_2047_p2 = ($signed(sext_ln813_11_fu_2043_p1) + $signed(sext_ln74_15_fu_1949_p1));

assign add_ln813_36_fu_2057_p2 = ($signed(sext_ln74_19_fu_1985_p1) + $signed(sext_ln813_fu_1994_p1));

assign add_ln813_37_fu_2067_p2 = ($signed(sext_ln813_13_fu_2063_p1) + $signed(sext_ln74_18_fu_1976_p1));

assign add_ln813_38_fu_2077_p2 = ($signed(sext_ln813_14_fu_2073_p1) + $signed(sext_ln813_12_fu_2053_p1));

assign add_ln813_39_fu_2087_p2 = ($signed(sext_ln813_15_fu_2083_p1) + $signed(sext_ln813_10_fu_2033_p1));

assign add_ln813_fu_1823_p2 = ($signed(sext_ln74_1_fu_1251_p1) + $signed(sext_ln74_fu_1242_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign batch_normalization_8_V_address10 = zext_ln74_fu_438_p1;

assign global_average_pooling1d_1_V_address0 = i_6_cast106_fu_1901_p1;

assign global_average_pooling1d_1_V_d0 = ($signed(add_ln813_39_fu_2087_p2) + $signed(sext_ln813_7_fu_1998_p1));

assign grp_fu_324_p1 = batch_normalization_8_V_q9;

assign grp_fu_324_p3 = grp_fu_324_p1[32'd31];

assign grp_fu_332_p1 = batch_normalization_8_V_q8;

assign grp_fu_332_p3 = grp_fu_332_p1[32'd31];

assign grp_fu_340_p1 = batch_normalization_8_V_q7;

assign grp_fu_340_p3 = grp_fu_340_p1[32'd31];

assign grp_fu_348_p1 = batch_normalization_8_V_q6;

assign grp_fu_348_p3 = grp_fu_348_p1[32'd31];

assign grp_fu_356_p1 = batch_normalization_8_V_q5;

assign grp_fu_356_p3 = grp_fu_356_p1[32'd31];

assign grp_fu_364_p1 = batch_normalization_8_V_q4;

assign grp_fu_364_p3 = grp_fu_364_p1[32'd31];

assign grp_fu_372_p1 = batch_normalization_8_V_q3;

assign grp_fu_372_p3 = grp_fu_372_p1[32'd31];

assign grp_fu_380_p1 = batch_normalization_8_V_q2;

assign grp_fu_380_p3 = grp_fu_380_p1[32'd31];

assign grp_fu_388_p1 = batch_normalization_8_V_q1;

assign grp_fu_388_p3 = grp_fu_388_p1[32'd31];

assign grp_fu_396_p1 = batch_normalization_8_V_q0;

assign grp_fu_396_p3 = grp_fu_396_p1[32'd31];

assign i_6_cast106_fu_1901_p1 = i_reg_2114_pp0_iter1_reg;

assign icmp_ln71_fu_417_p2 = ((ap_sig_allocacmp_i == 4'd11) ? 1'b1 : 1'b0);

assign mul_ln1303_10_fu_1091_p1 = 65'd6544712071;

assign mul_ln1303_11_fu_1319_p1 = 65'd6544712071;

assign mul_ln1303_12_fu_1369_p1 = 65'd6544712071;

assign mul_ln1303_13_fu_1427_p1 = 65'd6544712071;

assign mul_ln1303_14_fu_1477_p1 = 65'd6544712071;

assign mul_ln1303_15_fu_1527_p1 = 65'd6544712071;

assign mul_ln1303_16_fu_1577_p1 = 65'd6544712071;

assign mul_ln1303_17_fu_1627_p1 = 65'd6544712071;

assign mul_ln1303_18_fu_1677_p1 = 65'd6544712071;

assign mul_ln1303_19_fu_1727_p1 = 65'd6544712071;

assign mul_ln1303_1_fu_625_p1 = 65'd6544712071;

assign mul_ln1303_20_fu_1777_p1 = 65'd6544712071;

assign mul_ln1303_2_fu_675_p1 = 65'd6544712071;

assign mul_ln1303_3_fu_733_p1 = 65'd6544712071;

assign mul_ln1303_4_fu_783_p1 = 65'd6544712071;

assign mul_ln1303_5_fu_833_p1 = 65'd6544712071;

assign mul_ln1303_6_fu_883_p1 = 65'd6544712071;

assign mul_ln1303_7_fu_933_p1 = 65'd6544712071;

assign mul_ln1303_8_fu_991_p1 = 65'd6544712071;

assign mul_ln1303_9_fu_1041_p1 = 65'd6544712071;

assign mul_ln1303_fu_567_p1 = 65'd6544712071;

assign next_mul_fu_432_p2 = (ap_sig_allocacmp_phi_mul_load + 8'd21);

assign select_ln1303_10_fu_865_p3 = ((grp_fu_356_p3[0:0] == 1'b1) ? tmp_76_fu_845_p4 : tmp_77_fu_855_p4);

assign select_ln1303_11_fu_1276_p3 = ((tmp_75_reg_2257[0:0] == 1'b1) ? sub_ln1303_11_reg_2267 : tmp_77_reg_2262);

assign select_ln1303_12_fu_915_p3 = ((grp_fu_364_p3[0:0] == 1'b1) ? tmp_79_fu_895_p4 : tmp_80_fu_905_p4);

assign select_ln1303_13_fu_1285_p3 = ((tmp_78_reg_2272[0:0] == 1'b1) ? sub_ln1303_13_reg_2282 : tmp_80_reg_2277);

assign select_ln1303_14_fu_965_p3 = ((grp_fu_372_p3[0:0] == 1'b1) ? tmp_82_fu_945_p4 : tmp_83_fu_955_p4);

assign select_ln1303_15_fu_979_p3 = ((grp_fu_372_p3[0:0] == 1'b1) ? sub_ln1303_15_fu_973_p2 : tmp_83_fu_955_p4);

assign select_ln1303_16_fu_1023_p3 = ((grp_fu_380_p3[0:0] == 1'b1) ? tmp_85_fu_1003_p4 : tmp_86_fu_1013_p4);

assign select_ln1303_17_fu_1297_p3 = ((tmp_84_reg_2292[0:0] == 1'b1) ? sub_ln1303_17_reg_2302 : tmp_86_reg_2297);

assign select_ln1303_18_fu_1073_p3 = ((grp_fu_388_p3[0:0] == 1'b1) ? tmp_88_fu_1053_p4 : tmp_89_fu_1063_p4);

assign select_ln1303_19_fu_1306_p3 = ((tmp_87_reg_2307[0:0] == 1'b1) ? sub_ln1303_19_reg_2317 : tmp_89_reg_2312);

assign select_ln1303_1_fu_1237_p3 = ((tmp_reg_2192[0:0] == 1'b1) ? sub_ln1303_1_reg_2202 : tmp_62_reg_2197);

assign select_ln1303_20_fu_1123_p3 = ((grp_fu_396_p3[0:0] == 1'b1) ? tmp_91_fu_1103_p4 : tmp_92_fu_1113_p4);

assign select_ln1303_21_fu_1905_p3 = ((tmp_90_reg_2322[0:0] == 1'b1) ? sub_ln1303_21_reg_2332 : tmp_92_reg_2327);

assign select_ln1303_22_fu_1351_p3 = ((grp_fu_324_p3[0:0] == 1'b1) ? tmp_94_fu_1331_p4 : tmp_95_fu_1341_p4);

assign select_ln1303_23_fu_1914_p3 = ((tmp_93_reg_2387[0:0] == 1'b1) ? sub_ln1303_23_reg_2397 : tmp_95_reg_2392);

assign select_ln1303_24_fu_1401_p3 = ((grp_fu_332_p3[0:0] == 1'b1) ? tmp_97_fu_1381_p4 : tmp_98_fu_1391_p4);

assign select_ln1303_25_fu_1415_p3 = ((grp_fu_332_p3[0:0] == 1'b1) ? sub_ln1303_25_fu_1409_p2 : tmp_98_fu_1391_p4);

assign select_ln1303_26_fu_1459_p3 = ((grp_fu_340_p3[0:0] == 1'b1) ? tmp_100_fu_1439_p4 : tmp_101_fu_1449_p4);

assign select_ln1303_27_fu_1926_p3 = ((tmp_99_reg_2407[0:0] == 1'b1) ? sub_ln1303_27_reg_2417 : tmp_101_reg_2412);

assign select_ln1303_28_fu_1509_p3 = ((grp_fu_348_p3[0:0] == 1'b1) ? tmp_103_fu_1489_p4 : tmp_104_fu_1499_p4);

assign select_ln1303_29_fu_1935_p3 = ((tmp_102_reg_2422[0:0] == 1'b1) ? sub_ln1303_29_reg_2432 : tmp_104_reg_2427);

assign select_ln1303_2_fu_657_p3 = ((grp_fu_324_p3[0:0] == 1'b1) ? tmp_64_fu_637_p4 : tmp_65_fu_647_p4);

assign select_ln1303_30_fu_1559_p3 = ((grp_fu_356_p3[0:0] == 1'b1) ? tmp_106_fu_1539_p4 : tmp_107_fu_1549_p4);

assign select_ln1303_31_fu_1944_p3 = ((tmp_105_reg_2437[0:0] == 1'b1) ? sub_ln1303_31_reg_2447 : tmp_107_reg_2442);

assign select_ln1303_32_fu_1609_p3 = ((grp_fu_364_p3[0:0] == 1'b1) ? tmp_109_fu_1589_p4 : tmp_110_fu_1599_p4);

assign select_ln1303_33_fu_1953_p3 = ((tmp_108_reg_2452[0:0] == 1'b1) ? sub_ln1303_33_reg_2462 : tmp_110_reg_2457);

assign select_ln1303_34_fu_1659_p3 = ((grp_fu_372_p3[0:0] == 1'b1) ? tmp_112_fu_1639_p4 : tmp_113_fu_1649_p4);

assign select_ln1303_35_fu_1962_p3 = ((tmp_111_reg_2467[0:0] == 1'b1) ? sub_ln1303_35_reg_2477 : tmp_113_reg_2472);

assign select_ln1303_36_fu_1709_p3 = ((grp_fu_380_p3[0:0] == 1'b1) ? tmp_115_fu_1689_p4 : tmp_116_fu_1699_p4);

assign select_ln1303_37_fu_1971_p3 = ((tmp_114_reg_2482[0:0] == 1'b1) ? sub_ln1303_37_reg_2492 : tmp_116_reg_2487);

assign select_ln1303_38_fu_1759_p3 = ((grp_fu_388_p3[0:0] == 1'b1) ? tmp_118_fu_1739_p4 : tmp_119_fu_1749_p4);

assign select_ln1303_39_fu_1980_p3 = ((tmp_117_reg_2497[0:0] == 1'b1) ? sub_ln1303_39_reg_2507 : tmp_119_reg_2502);

assign select_ln1303_3_fu_1246_p3 = ((tmp_63_reg_2207[0:0] == 1'b1) ? sub_ln1303_3_reg_2217 : tmp_65_reg_2212);

assign select_ln1303_40_fu_1809_p3 = ((grp_fu_396_p3[0:0] == 1'b1) ? tmp_121_fu_1789_p4 : tmp_122_fu_1799_p4);

assign select_ln1303_41_fu_1989_p3 = ((tmp_120_reg_2512[0:0] == 1'b1) ? sub_ln1303_41_reg_2522 : tmp_122_reg_2517);

assign select_ln1303_4_fu_707_p3 = ((grp_fu_332_p3[0:0] == 1'b1) ? tmp_67_fu_687_p4 : tmp_68_fu_697_p4);

assign select_ln1303_5_fu_721_p3 = ((grp_fu_332_p3[0:0] == 1'b1) ? sub_ln1303_5_fu_715_p2 : tmp_68_fu_697_p4);

assign select_ln1303_6_fu_765_p3 = ((grp_fu_340_p3[0:0] == 1'b1) ? tmp_70_fu_745_p4 : tmp_71_fu_755_p4);

assign select_ln1303_7_fu_1258_p3 = ((tmp_69_reg_2227[0:0] == 1'b1) ? sub_ln1303_7_reg_2237 : tmp_71_reg_2232);

assign select_ln1303_8_fu_815_p3 = ((grp_fu_348_p3[0:0] == 1'b1) ? tmp_73_fu_795_p4 : tmp_74_fu_805_p4);

assign select_ln1303_9_fu_1267_p3 = ((tmp_72_reg_2242[0:0] == 1'b1) ? sub_ln1303_9_reg_2252 : tmp_74_reg_2247);

assign select_ln1303_fu_607_p3 = ((tmp_fu_579_p3[0:0] == 1'b1) ? tmp_61_fu_587_p4 : tmp_62_fu_597_p4);

assign sext_ln74_10_fu_1910_p1 = $signed(select_ln1303_21_fu_1905_p3);

assign sext_ln74_11_fu_1919_p1 = $signed(select_ln1303_23_fu_1914_p3);

assign sext_ln74_12_fu_1923_p1 = $signed(select_ln1303_25_reg_2402);

assign sext_ln74_13_fu_1931_p1 = $signed(select_ln1303_27_fu_1926_p3);

assign sext_ln74_14_fu_1940_p1 = $signed(select_ln1303_29_fu_1935_p3);

assign sext_ln74_15_fu_1949_p1 = $signed(select_ln1303_31_fu_1944_p3);

assign sext_ln74_16_fu_1958_p1 = $signed(select_ln1303_33_fu_1953_p3);

assign sext_ln74_17_fu_1967_p1 = $signed(select_ln1303_35_fu_1962_p3);

assign sext_ln74_18_fu_1976_p1 = $signed(select_ln1303_37_fu_1971_p3);

assign sext_ln74_19_fu_1985_p1 = $signed(select_ln1303_39_fu_1980_p3);

assign sext_ln74_1_fu_1251_p1 = $signed(select_ln1303_3_fu_1246_p3);

assign sext_ln74_2_fu_1255_p1 = $signed(select_ln1303_5_reg_2222);

assign sext_ln74_3_fu_1263_p1 = $signed(select_ln1303_7_fu_1258_p3);

assign sext_ln74_4_fu_1272_p1 = $signed(select_ln1303_9_fu_1267_p3);

assign sext_ln74_5_fu_1281_p1 = $signed(select_ln1303_11_fu_1276_p3);

assign sext_ln74_6_fu_1290_p1 = $signed(select_ln1303_13_fu_1285_p3);

assign sext_ln74_7_fu_1294_p1 = $signed(select_ln1303_15_reg_2287);

assign sext_ln74_8_fu_1302_p1 = $signed(select_ln1303_17_fu_1297_p3);

assign sext_ln74_9_fu_1311_p1 = $signed(select_ln1303_19_fu_1306_p3);

assign sext_ln74_fu_1242_p1 = $signed(select_ln1303_1_fu_1237_p3);

assign sext_ln813_10_fu_2033_p1 = $signed(add_ln813_33_fu_2027_p2);

assign sext_ln813_11_fu_2043_p1 = $signed(add_ln813_34_fu_2037_p2);

assign sext_ln813_12_fu_2053_p1 = $signed(add_ln813_35_fu_2047_p2);

assign sext_ln813_13_fu_2063_p1 = $signed(add_ln813_36_fu_2057_p2);

assign sext_ln813_14_fu_2073_p1 = $signed(add_ln813_37_fu_2067_p2);

assign sext_ln813_15_fu_2083_p1 = $signed(add_ln813_38_fu_2077_p2);

assign sext_ln813_1_fu_1829_p1 = $signed(add_ln813_fu_1823_p2);

assign sext_ln813_2_fu_1839_p1 = $signed(add_ln813_21_fu_1833_p2);

assign sext_ln813_3_fu_1855_p1 = $signed(add_ln813_23_fu_1849_p2);

assign sext_ln813_4_fu_1865_p1 = $signed(add_ln813_24_fu_1859_p2);

assign sext_ln813_5_fu_1875_p1 = $signed(add_ln813_25_fu_1869_p2);

assign sext_ln813_6_fu_1891_p1 = $signed(add_ln813_27_fu_1885_p2);

assign sext_ln813_7_fu_1998_p1 = $signed(add_ln813_28_reg_2527);

assign sext_ln813_8_fu_2007_p1 = $signed(add_ln813_29_fu_2001_p2);

assign sext_ln813_9_fu_2017_p1 = $signed(add_ln813_30_fu_2011_p2);

assign sext_ln813_fu_1994_p1 = $signed(select_ln1303_41_fu_1989_p3);

assign sub_ln1303_10_fu_839_p2 = (65'd0 - mul_ln1303_5_fu_833_p2);

assign sub_ln1303_11_fu_873_p2 = (28'd0 - select_ln1303_10_fu_865_p3);

assign sub_ln1303_12_fu_889_p2 = (65'd0 - mul_ln1303_6_fu_883_p2);

assign sub_ln1303_13_fu_923_p2 = (28'd0 - select_ln1303_12_fu_915_p3);

assign sub_ln1303_14_fu_939_p2 = (65'd0 - mul_ln1303_7_fu_933_p2);

assign sub_ln1303_15_fu_973_p2 = (28'd0 - select_ln1303_14_fu_965_p3);

assign sub_ln1303_16_fu_997_p2 = (65'd0 - mul_ln1303_8_fu_991_p2);

assign sub_ln1303_17_fu_1031_p2 = (28'd0 - select_ln1303_16_fu_1023_p3);

assign sub_ln1303_18_fu_1047_p2 = (65'd0 - mul_ln1303_9_fu_1041_p2);

assign sub_ln1303_19_fu_1081_p2 = (28'd0 - select_ln1303_18_fu_1073_p3);

assign sub_ln1303_1_fu_615_p2 = (28'd0 - select_ln1303_fu_607_p3);

assign sub_ln1303_20_fu_1097_p2 = (65'd0 - mul_ln1303_10_fu_1091_p2);

assign sub_ln1303_21_fu_1131_p2 = (28'd0 - select_ln1303_20_fu_1123_p3);

assign sub_ln1303_22_fu_1325_p2 = (65'd0 - mul_ln1303_11_fu_1319_p2);

assign sub_ln1303_23_fu_1359_p2 = (28'd0 - select_ln1303_22_fu_1351_p3);

assign sub_ln1303_24_fu_1375_p2 = (65'd0 - mul_ln1303_12_fu_1369_p2);

assign sub_ln1303_25_fu_1409_p2 = (28'd0 - select_ln1303_24_fu_1401_p3);

assign sub_ln1303_26_fu_1433_p2 = (65'd0 - mul_ln1303_13_fu_1427_p2);

assign sub_ln1303_27_fu_1467_p2 = (28'd0 - select_ln1303_26_fu_1459_p3);

assign sub_ln1303_28_fu_1483_p2 = (65'd0 - mul_ln1303_14_fu_1477_p2);

assign sub_ln1303_29_fu_1517_p2 = (28'd0 - select_ln1303_28_fu_1509_p3);

assign sub_ln1303_2_fu_631_p2 = (65'd0 - mul_ln1303_1_fu_625_p2);

assign sub_ln1303_30_fu_1533_p2 = (65'd0 - mul_ln1303_15_fu_1527_p2);

assign sub_ln1303_31_fu_1567_p2 = (28'd0 - select_ln1303_30_fu_1559_p3);

assign sub_ln1303_32_fu_1583_p2 = (65'd0 - mul_ln1303_16_fu_1577_p2);

assign sub_ln1303_33_fu_1617_p2 = (28'd0 - select_ln1303_32_fu_1609_p3);

assign sub_ln1303_34_fu_1633_p2 = (65'd0 - mul_ln1303_17_fu_1627_p2);

assign sub_ln1303_35_fu_1667_p2 = (28'd0 - select_ln1303_34_fu_1659_p3);

assign sub_ln1303_36_fu_1683_p2 = (65'd0 - mul_ln1303_18_fu_1677_p2);

assign sub_ln1303_37_fu_1717_p2 = (28'd0 - select_ln1303_36_fu_1709_p3);

assign sub_ln1303_38_fu_1733_p2 = (65'd0 - mul_ln1303_19_fu_1727_p2);

assign sub_ln1303_39_fu_1767_p2 = (28'd0 - select_ln1303_38_fu_1759_p3);

assign sub_ln1303_3_fu_665_p2 = (28'd0 - select_ln1303_2_fu_657_p3);

assign sub_ln1303_40_fu_1783_p2 = (65'd0 - mul_ln1303_20_fu_1777_p2);

assign sub_ln1303_41_fu_1817_p2 = (28'd0 - select_ln1303_40_fu_1809_p3);

assign sub_ln1303_4_fu_681_p2 = (65'd0 - mul_ln1303_2_fu_675_p2);

assign sub_ln1303_5_fu_715_p2 = (28'd0 - select_ln1303_4_fu_707_p3);

assign sub_ln1303_6_fu_739_p2 = (65'd0 - mul_ln1303_3_fu_733_p2);

assign sub_ln1303_7_fu_773_p2 = (28'd0 - select_ln1303_6_fu_765_p3);

assign sub_ln1303_8_fu_789_p2 = (65'd0 - mul_ln1303_4_fu_783_p2);

assign sub_ln1303_9_fu_823_p2 = (28'd0 - select_ln1303_8_fu_815_p3);

assign sub_ln1303_fu_573_p2 = (65'd0 - mul_ln1303_fu_567_p2);

assign tmp_100_fu_1439_p4 = {{sub_ln1303_26_fu_1433_p2[64:37]}};

assign tmp_101_fu_1449_p4 = {{mul_ln1303_13_fu_1427_p2[64:37]}};

assign tmp_103_fu_1489_p4 = {{sub_ln1303_28_fu_1483_p2[64:37]}};

assign tmp_104_fu_1499_p4 = {{mul_ln1303_14_fu_1477_p2[64:37]}};

assign tmp_106_fu_1539_p4 = {{sub_ln1303_30_fu_1533_p2[64:37]}};

assign tmp_107_fu_1549_p4 = {{mul_ln1303_15_fu_1527_p2[64:37]}};

assign tmp_109_fu_1589_p4 = {{sub_ln1303_32_fu_1583_p2[64:37]}};

assign tmp_110_fu_1599_p4 = {{mul_ln1303_16_fu_1577_p2[64:37]}};

assign tmp_112_fu_1639_p4 = {{sub_ln1303_34_fu_1633_p2[64:37]}};

assign tmp_113_fu_1649_p4 = {{mul_ln1303_17_fu_1627_p2[64:37]}};

assign tmp_115_fu_1689_p4 = {{sub_ln1303_36_fu_1683_p2[64:37]}};

assign tmp_116_fu_1699_p4 = {{mul_ln1303_18_fu_1677_p2[64:37]}};

assign tmp_118_fu_1739_p4 = {{sub_ln1303_38_fu_1733_p2[64:37]}};

assign tmp_119_fu_1749_p4 = {{mul_ln1303_19_fu_1727_p2[64:37]}};

assign tmp_121_fu_1789_p4 = {{sub_ln1303_40_fu_1783_p2[64:37]}};

assign tmp_122_fu_1799_p4 = {{mul_ln1303_20_fu_1777_p2[64:37]}};

assign tmp_61_fu_587_p4 = {{sub_ln1303_fu_573_p2[64:37]}};

assign tmp_62_fu_597_p4 = {{mul_ln1303_fu_567_p2[64:37]}};

assign tmp_64_fu_637_p4 = {{sub_ln1303_2_fu_631_p2[64:37]}};

assign tmp_65_fu_647_p4 = {{mul_ln1303_1_fu_625_p2[64:37]}};

assign tmp_67_fu_687_p4 = {{sub_ln1303_4_fu_681_p2[64:37]}};

assign tmp_68_fu_697_p4 = {{mul_ln1303_2_fu_675_p2[64:37]}};

assign tmp_70_fu_745_p4 = {{sub_ln1303_6_fu_739_p2[64:37]}};

assign tmp_71_fu_755_p4 = {{mul_ln1303_3_fu_733_p2[64:37]}};

assign tmp_73_fu_795_p4 = {{sub_ln1303_8_fu_789_p2[64:37]}};

assign tmp_74_fu_805_p4 = {{mul_ln1303_4_fu_783_p2[64:37]}};

assign tmp_76_fu_845_p4 = {{sub_ln1303_10_fu_839_p2[64:37]}};

assign tmp_77_fu_855_p4 = {{mul_ln1303_5_fu_833_p2[64:37]}};

assign tmp_79_fu_895_p4 = {{sub_ln1303_12_fu_889_p2[64:37]}};

assign tmp_80_fu_905_p4 = {{mul_ln1303_6_fu_883_p2[64:37]}};

assign tmp_82_fu_945_p4 = {{sub_ln1303_14_fu_939_p2[64:37]}};

assign tmp_83_fu_955_p4 = {{mul_ln1303_7_fu_933_p2[64:37]}};

assign tmp_85_fu_1003_p4 = {{sub_ln1303_16_fu_997_p2[64:37]}};

assign tmp_86_fu_1013_p4 = {{mul_ln1303_8_fu_991_p2[64:37]}};

assign tmp_88_fu_1053_p4 = {{sub_ln1303_18_fu_1047_p2[64:37]}};

assign tmp_89_fu_1063_p4 = {{mul_ln1303_9_fu_1041_p2[64:37]}};

assign tmp_91_fu_1103_p4 = {{sub_ln1303_20_fu_1097_p2[64:37]}};

assign tmp_92_fu_1113_p4 = {{mul_ln1303_10_fu_1091_p2[64:37]}};

assign tmp_94_fu_1331_p4 = {{sub_ln1303_22_fu_1325_p2[64:37]}};

assign tmp_95_fu_1341_p4 = {{mul_ln1303_11_fu_1319_p2[64:37]}};

assign tmp_97_fu_1381_p4 = {{sub_ln1303_24_fu_1375_p2[64:37]}};

assign tmp_98_fu_1391_p4 = {{mul_ln1303_12_fu_1369_p2[64:37]}};

assign tmp_fu_579_p1 = batch_normalization_8_V_q10;

assign tmp_fu_579_p3 = tmp_fu_579_p1[32'd31];

assign zext_ln74_10_fu_548_p1 = add_ln74_9_fu_542_p2;

assign zext_ln74_11_fu_1142_p1 = add_ln74_10_fu_1137_p2;

assign zext_ln74_12_fu_1152_p1 = add_ln74_11_fu_1147_p2;

assign zext_ln74_13_fu_1162_p1 = add_ln74_12_fu_1157_p2;

assign zext_ln74_14_fu_1172_p1 = add_ln74_13_fu_1167_p2;

assign zext_ln74_15_fu_1182_p1 = add_ln74_14_fu_1177_p2;

assign zext_ln74_16_fu_1192_p1 = add_ln74_15_fu_1187_p2;

assign zext_ln74_17_fu_1202_p1 = add_ln74_16_fu_1197_p2;

assign zext_ln74_18_fu_1212_p1 = add_ln74_17_fu_1207_p2;

assign zext_ln74_19_fu_1222_p1 = add_ln74_18_fu_1217_p2;

assign zext_ln74_1_fu_449_p1 = add_ln74_fu_443_p2;

assign zext_ln74_20_fu_1232_p1 = add_ln74_19_fu_1227_p2;

assign zext_ln74_2_fu_460_p1 = add_ln74_1_fu_454_p2;

assign zext_ln74_3_fu_471_p1 = add_ln74_2_fu_465_p2;

assign zext_ln74_4_fu_482_p1 = add_ln74_3_fu_476_p2;

assign zext_ln74_5_fu_493_p1 = add_ln74_4_fu_487_p2;

assign zext_ln74_6_fu_504_p1 = add_ln74_5_fu_498_p2;

assign zext_ln74_7_fu_515_p1 = add_ln74_6_fu_509_p2;

assign zext_ln74_8_fu_526_p1 = add_ln74_7_fu_520_p2;

assign zext_ln74_9_fu_537_p1 = add_ln74_8_fu_531_p2;

assign zext_ln74_fu_438_p1 = ap_sig_allocacmp_phi_mul_load;

endmodule //CNN_CNN_Pipeline_VITIS_LOOP_71_1
