// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_channel_pool_0_loop_for_weight_pool_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        batch_normalization_5_V_address0,
        batch_normalization_5_V_ce0,
        batch_normalization_5_V_q0,
        batch_normalization_5_V_address1,
        batch_normalization_5_V_ce1,
        batch_normalization_5_V_q1,
        max_pooling1d_3_V_address0,
        max_pooling1d_3_V_ce0,
        max_pooling1d_3_V_we0,
        max_pooling1d_3_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] batch_normalization_5_V_address0;
output   batch_normalization_5_V_ce0;
input  [31:0] batch_normalization_5_V_q0;
output  [12:0] batch_normalization_5_V_address1;
output   batch_normalization_5_V_ce1;
input  [31:0] batch_normalization_5_V_q1;
output  [11:0] max_pooling1d_3_V_address0;
output   max_pooling1d_3_V_ce0;
output   max_pooling1d_3_V_we0;
output  [31:0] max_pooling1d_3_V_d0;

reg ap_idle;
reg batch_normalization_5_V_ce0;
reg batch_normalization_5_V_ce1;
reg max_pooling1d_3_V_ce0;
reg max_pooling1d_3_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln8_fu_122_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] select_ln11_fu_146_p3;
reg   [6:0] select_ln11_reg_301;
reg   [6:0] select_ln11_reg_301_pp0_iter1_reg;
wire   [11:0] grp_fu_268_p3;
reg   [11:0] add_ln19_reg_337;
wire   [63:0] zext_ln16_fu_211_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln16_1_fu_220_p1;
wire   [63:0] zext_ln20_fu_254_p1;
reg   [6:0] y_fu_54;
wire   [6:0] add_ln21_fu_176_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_y_load;
reg   [5:0] z_fu_58;
wire   [5:0] select_ln11_1_fu_160_p3;
reg   [5:0] ap_sig_allocacmp_z_load;
reg   [11:0] indvar_flatten65_fu_62;
wire   [11:0] add_ln8_fu_128_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten65_load;
wire   [0:0] icmp_ln11_fu_140_p2;
wire   [5:0] add_ln8_1_fu_154_p2;
wire   [7:0] tmp_s_fu_200_p3;
wire   [12:0] grp_fu_258_p3;
(* use_dsp48 = "no" *) wire   [12:0] add_ln15_1_fu_215_p2;
wire   [0:0] icmp_ln1649_fu_225_p2;
wire   [31:0] select_ln17_fu_231_p3;
wire   [0:0] icmp_ln1649_1_fu_239_p2;
wire   [5:0] grp_fu_258_p0;
wire   [7:0] grp_fu_258_p1;
wire   [7:0] grp_fu_258_p2;
wire   [5:0] grp_fu_268_p0;
wire   [6:0] grp_fu_268_p1;
wire   [6:0] grp_fu_268_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [12:0] grp_fu_258_p00;
wire   [12:0] grp_fu_258_p20;
wire   [11:0] grp_fu_268_p00;
wire   [11:0] grp_fu_268_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

CNN_mac_muladd_6ns_8ns_8ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mac_muladd_6ns_8ns_8ns_13_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_258_p0),
    .din1(grp_fu_258_p1),
    .din2(grp_fu_258_p2),
    .ce(1'b1),
    .dout(grp_fu_258_p3)
);

CNN_mac_muladd_6ns_7ns_7ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 12 ))
mac_muladd_6ns_7ns_7ns_12_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_268_p0),
    .din1(grp_fu_268_p1),
    .din2(grp_fu_268_p2),
    .ce(1'b1),
    .dout(grp_fu_268_p3)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln8_fu_122_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten65_fu_62 <= add_ln8_fu_128_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten65_fu_62 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln8_fu_122_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_54 <= add_ln21_fu_176_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_54 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln8_fu_122_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            z_fu_58 <= select_ln11_1_fu_160_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            z_fu_58 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln19_reg_337 <= grp_fu_268_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln11_reg_301_pp0_iter1_reg <= select_ln11_reg_301;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln8_fu_122_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln11_reg_301 <= select_ln11_fu_146_p3;
    end
end

always @ (*) begin
    if (((icmp_ln8_fu_122_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten65_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten65_load = indvar_flatten65_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_load = 7'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_z_load = 6'd0;
    end else begin
        ap_sig_allocacmp_z_load = z_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        batch_normalization_5_V_ce0 = 1'b1;
    end else begin
        batch_normalization_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        batch_normalization_5_V_ce1 = 1'b1;
    end else begin
        batch_normalization_5_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        max_pooling1d_3_V_ce0 = 1'b1;
    end else begin
        max_pooling1d_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        max_pooling1d_3_V_we0 = 1'b1;
    end else begin
        max_pooling1d_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_1_fu_215_p2 = (grp_fu_258_p3 + 13'd1);

assign add_ln21_fu_176_p2 = (select_ln11_fu_146_p3 + 7'd1);

assign add_ln8_1_fu_154_p2 = (ap_sig_allocacmp_z_load + 6'd1);

assign add_ln8_fu_128_p2 = (ap_sig_allocacmp_indvar_flatten65_load + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign batch_normalization_5_V_address0 = zext_ln16_1_fu_220_p1;

assign batch_normalization_5_V_address1 = zext_ln16_fu_211_p1;

assign grp_fu_258_p0 = grp_fu_258_p00;

assign grp_fu_258_p00 = select_ln11_1_fu_160_p3;

assign grp_fu_258_p1 = 13'd173;

assign grp_fu_258_p2 = grp_fu_258_p20;

assign grp_fu_258_p20 = tmp_s_fu_200_p3;

assign grp_fu_268_p0 = grp_fu_268_p00;

assign grp_fu_268_p00 = select_ln11_1_fu_160_p3;

assign grp_fu_268_p1 = 12'd86;

assign grp_fu_268_p2 = grp_fu_268_p20;

assign grp_fu_268_p20 = select_ln11_reg_301_pp0_iter1_reg;

assign icmp_ln11_fu_140_p2 = ((ap_sig_allocacmp_y_load == 7'd86) ? 1'b1 : 1'b0);

assign icmp_ln1649_1_fu_239_p2 = (($signed(batch_normalization_5_V_q0) > $signed(select_ln17_fu_231_p3)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_225_p2 = (($signed(batch_normalization_5_V_q1) > $signed(32'd4294311936)) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_122_p2 = ((ap_sig_allocacmp_indvar_flatten65_load == 12'd2752) ? 1'b1 : 1'b0);

assign max_pooling1d_3_V_address0 = zext_ln20_fu_254_p1;

assign max_pooling1d_3_V_d0 = ((icmp_ln1649_1_fu_239_p2[0:0] == 1'b1) ? batch_normalization_5_V_q0 : select_ln17_fu_231_p3);

assign select_ln11_1_fu_160_p3 = ((icmp_ln11_fu_140_p2[0:0] == 1'b1) ? add_ln8_1_fu_154_p2 : ap_sig_allocacmp_z_load);

assign select_ln11_fu_146_p3 = ((icmp_ln11_fu_140_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_y_load);

assign select_ln17_fu_231_p3 = ((icmp_ln1649_fu_225_p2[0:0] == 1'b1) ? batch_normalization_5_V_q1 : 32'd4294311936);

assign tmp_s_fu_200_p3 = {{select_ln11_reg_301_pp0_iter1_reg}, {1'd0}};

assign zext_ln16_1_fu_220_p1 = add_ln15_1_fu_215_p2;

assign zext_ln16_fu_211_p1 = grp_fu_258_p3;

assign zext_ln20_fu_254_p1 = add_ln19_reg_337;

endmodule //CNN_CNN_Pipeline_loop_for_channel_pool_0_loop_for_weight_pool_0
