-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_loop_for_3_channel_pad_3_loop_for_channel_pad_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    OutPadConv3_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    OutPadConv3_V_ce0 : OUT STD_LOGIC;
    OutPadConv3_V_we0 : OUT STD_LOGIC;
    OutPadConv3_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    max_pooling1d_5_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    max_pooling1d_5_V_ce0 : OUT STD_LOGIC;
    max_pooling1d_5_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of CNN_CNN_Pipeline_loop_for_3_channel_pad_3_loop_for_channel_pad_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_B80 : STD_LOGIC_VECTOR (11 downto 0) := "101110000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv12_15 : STD_LOGIC_VECTOR (11 downto 0) := "000000010101";
    constant ap_const_lv12_17 : STD_LOGIC_VECTOR (11 downto 0) := "000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln118_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln118_fu_130_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln118_reg_266 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln118_reg_266_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln118_fu_152_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln121_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln121_reg_285 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln121_reg_285_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln121_1_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln121_1_reg_290 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln121_1_reg_290_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_233_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln121_reg_300 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln121_1_fu_203_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln121_fu_211_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_fu_50 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln120_fu_156_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n_load : STD_LOGIC_VECTOR (4 downto 0);
    signal c_fu_54 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln118_1_fu_144_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten236_fu_58 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln118_fu_112_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten236_load : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln120_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln118_1_fu_138_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal n_7_cast_fu_180_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln121_1_fu_193_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln121_1_fu_203_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_224_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln121_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_224_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_224_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_233_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_233_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_233_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_233_p20 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component CNN_mac_muladd_8ns_5ns_6s_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component CNN_mac_muladd_8ns_5ns_5ns_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8ns_5ns_6s_12_4_1_U88 : component CNN_mac_muladd_8ns_5ns_6s_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 6,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_224_p0,
        din1 => grp_fu_224_p1,
        din2 => add_ln121_1_fu_193_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_224_p3);

    mac_muladd_8ns_5ns_5ns_12_4_1_U89 : component CNN_mac_muladd_8ns_5ns_5ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_233_p0,
        din1 => grp_fu_233_p1,
        din2 => grp_fu_233_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_233_p3);

    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    c_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_54 <= select_ln118_1_fu_144_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_54 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten236_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten236_fu_58 <= add_ln118_fu_112_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten236_fu_58 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    n_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_fu_50 <= add_ln120_fu_156_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_50 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                add_ln121_reg_300 <= grp_fu_233_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln118_reg_266_pp0_iter1_reg <= select_ln118_reg_266;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln121_1_reg_290 <= icmp_ln121_1_fu_188_p2;
                icmp_ln121_1_reg_290_pp0_iter3_reg <= icmp_ln121_1_reg_290;
                icmp_ln121_reg_285 <= icmp_ln121_fu_183_p2;
                icmp_ln121_reg_285_pp0_iter3_reg <= icmp_ln121_reg_285;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln118_fu_106_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln118_reg_266 <= select_ln118_fu_130_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    OutPadConv3_V_address0 <= zext_ln121_fu_211_p1(12 - 1 downto 0);

    OutPadConv3_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            OutPadConv3_V_ce0 <= ap_const_logic_1;
        else 
            OutPadConv3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    OutPadConv3_V_d0 <= 
        ap_const_lv32_0 when (or_ln121_fu_207_p2(0) = '1') else 
        max_pooling1d_5_V_q0;

    OutPadConv3_V_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            OutPadConv3_V_we0 <= ap_const_logic_1;
        else 
            OutPadConv3_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln118_1_fu_138_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv8_1));
    add_ln118_fu_112_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten236_load) + unsigned(ap_const_lv12_1));
    add_ln120_fu_156_p2 <= std_logic_vector(unsigned(select_ln118_fu_130_p3) + unsigned(ap_const_lv5_1));
    add_ln121_1_fu_193_p2 <= std_logic_vector(unsigned(n_7_cast_fu_180_p1) + unsigned(ap_const_lv6_3F));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln118_fu_106_p2)
    begin
        if (((icmp_ln118_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_54)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_54;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten236_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten236_fu_58)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten236_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten236_load <= indvar_flatten236_fu_58;
        end if; 
    end process;


    ap_sig_allocacmp_n_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, n_fu_50, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_n_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_n_load <= n_fu_50;
        end if; 
    end process;

    grp_fu_224_p0 <= zext_ln118_fu_152_p1(8 - 1 downto 0);
    grp_fu_224_p1 <= ap_const_lv12_15(5 - 1 downto 0);
    grp_fu_233_p0 <= zext_ln118_fu_152_p1(8 - 1 downto 0);
    grp_fu_233_p1 <= ap_const_lv12_17(5 - 1 downto 0);
    grp_fu_233_p2 <= grp_fu_233_p20(5 - 1 downto 0);
    grp_fu_233_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln118_reg_266_pp0_iter1_reg),12));
    icmp_ln118_fu_106_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten236_load = ap_const_lv12_B80) else "0";
    icmp_ln120_fu_124_p2 <= "1" when (ap_sig_allocacmp_n_load = ap_const_lv5_17) else "0";
    icmp_ln121_1_fu_188_p2 <= "1" when (unsigned(select_ln118_reg_266_pp0_iter1_reg) > unsigned(ap_const_lv5_15)) else "0";
    icmp_ln121_fu_183_p2 <= "1" when (select_ln118_reg_266_pp0_iter1_reg = ap_const_lv5_0) else "0";
    max_pooling1d_5_V_address0 <= zext_ln121_1_fu_203_p1(12 - 1 downto 0);

    max_pooling1d_5_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            max_pooling1d_5_V_ce0 <= ap_const_logic_1;
        else 
            max_pooling1d_5_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    n_7_cast_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln118_reg_266_pp0_iter1_reg),6));
    or_ln121_fu_207_p2 <= (icmp_ln121_reg_285_pp0_iter3_reg or icmp_ln121_1_reg_290_pp0_iter3_reg);
    select_ln118_1_fu_144_p3 <= 
        add_ln118_1_fu_138_p2 when (icmp_ln120_fu_124_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln118_fu_130_p3 <= 
        ap_const_lv5_0 when (icmp_ln120_fu_124_p2(0) = '1') else 
        ap_sig_allocacmp_n_load;
    zext_ln118_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln118_1_fu_144_p3),12));
    zext_ln121_1_fu_203_p0 <= grp_fu_224_p3;
    zext_ln121_1_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln121_1_fu_203_p0),64));
    zext_ln121_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln121_reg_300),64));
end behav;
