-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_VITIS_LOOP_71_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    batch_normalization_8_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce0 : OUT STD_LOGIC;
    batch_normalization_8_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce1 : OUT STD_LOGIC;
    batch_normalization_8_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce2 : OUT STD_LOGIC;
    batch_normalization_8_V_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce3 : OUT STD_LOGIC;
    batch_normalization_8_V_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce4 : OUT STD_LOGIC;
    batch_normalization_8_V_q4 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce5 : OUT STD_LOGIC;
    batch_normalization_8_V_q5 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce6 : OUT STD_LOGIC;
    batch_normalization_8_V_q6 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce7 : OUT STD_LOGIC;
    batch_normalization_8_V_q7 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address8 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce8 : OUT STD_LOGIC;
    batch_normalization_8_V_q8 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce9 : OUT STD_LOGIC;
    batch_normalization_8_V_q9 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_8_V_address10 : OUT STD_LOGIC_VECTOR (7 downto 0);
    batch_normalization_8_V_ce10 : OUT STD_LOGIC;
    batch_normalization_8_V_q10 : IN STD_LOGIC_VECTOR (31 downto 0);
    global_average_pooling1d_1_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    global_average_pooling1d_1_V_ce0 : OUT STD_LOGIC;
    global_average_pooling1d_1_V_we0 : OUT STD_LOGIC;
    global_average_pooling1d_1_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of CNN_CNN_Pipeline_VITIS_LOOP_71_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_15 : STD_LOGIC_VECTOR (7 downto 0) := "00010101";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv8_8 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv65_186186187 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000110000110000110000110000110000111";
    constant ap_const_lv65_0 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv8_B : STD_LOGIC_VECTOR (7 downto 0) := "00001011";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv8_E : STD_LOGIC_VECTOR (7 downto 0) := "00001110";
    constant ap_const_lv8_F : STD_LOGIC_VECTOR (7 downto 0) := "00001111";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv8_11 : STD_LOGIC_VECTOR (7 downto 0) := "00010001";
    constant ap_const_lv8_12 : STD_LOGIC_VECTOR (7 downto 0) := "00010010";
    constant ap_const_lv8_13 : STD_LOGIC_VECTOR (7 downto 0) := "00010011";
    constant ap_const_lv8_14 : STD_LOGIC_VECTOR (7 downto 0) := "00010100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln71_reg_2119 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_reg_2114 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_reg_2114_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln71_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_mul_load_reg_2123 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_579_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_2192 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_62_fu_597_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_62_reg_2197 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_1_fu_615_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_1_reg_2202 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_324_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_reg_2207 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_65_fu_647_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_65_reg_2212 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_3_fu_665_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_3_reg_2217 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_5_fu_721_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_5_reg_2222 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_340_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_69_reg_2227 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_71_fu_755_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_71_reg_2232 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_7_fu_773_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_7_reg_2237 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_348_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_72_reg_2242 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_74_fu_805_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_74_reg_2247 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_9_fu_823_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_9_reg_2252 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_356_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_75_reg_2257 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_77_fu_855_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_77_reg_2262 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_11_fu_873_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_11_reg_2267 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_364_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_78_reg_2272 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_fu_905_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_80_reg_2277 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_13_fu_923_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_13_reg_2282 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_15_fu_979_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_15_reg_2287 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_380_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_reg_2292 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_86_fu_1013_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_86_reg_2297 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_17_fu_1031_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_17_reg_2302 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_388_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_87_reg_2307 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_89_fu_1063_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_89_reg_2312 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_19_fu_1081_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_19_reg_2317 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_396_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_90_reg_2322 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_92_fu_1113_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_92_reg_2327 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_21_fu_1131_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_21_reg_2332 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_93_reg_2387 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_95_fu_1341_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_95_reg_2392 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_23_fu_1359_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_23_reg_2397 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_25_fu_1415_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_25_reg_2402 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_99_reg_2407 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_101_fu_1449_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_101_reg_2412 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_27_fu_1467_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_27_reg_2417 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_102_reg_2422 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_104_fu_1499_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_104_reg_2427 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_29_fu_1517_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_29_reg_2432 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_105_reg_2437 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_107_fu_1549_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_107_reg_2442 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_31_fu_1567_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_31_reg_2447 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_108_reg_2452 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_110_fu_1599_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_110_reg_2457 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_33_fu_1617_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_33_reg_2462 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_372_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_111_reg_2467 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_113_fu_1649_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_113_reg_2472 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_35_fu_1667_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_35_reg_2477 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_114_reg_2482 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_116_fu_1699_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_116_reg_2487 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_37_fu_1717_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_37_reg_2492 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_117_reg_2497 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_119_fu_1749_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_119_reg_2502 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_39_fu_1767_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_39_reg_2507 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_120_reg_2512 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_122_fu_1799_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_122_reg_2517 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_41_fu_1817_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_41_reg_2522 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln813_28_fu_1895_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln813_28_reg_2527 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln74_fu_438_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln74_1_fu_449_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_2_fu_460_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_3_fu_471_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_4_fu_482_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_5_fu_493_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_6_fu_504_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_7_fu_515_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_8_fu_526_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_9_fu_537_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_10_fu_548_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_11_fu_1142_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln74_12_fu_1152_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_13_fu_1162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_14_fu_1172_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_15_fu_1182_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_16_fu_1192_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_17_fu_1202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_18_fu_1212_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_19_fu_1222_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln74_20_fu_1232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_6_cast106_fu_1901_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_mul_fu_90 : STD_LOGIC_VECTOR (7 downto 0);
    signal next_mul_fu_432_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_mul_load : STD_LOGIC_VECTOR (7 downto 0);
    signal hs_fu_94 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln71_fu_423_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_324_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_332_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_340_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_348_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_356_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_364_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_372_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_380_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_388_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_396_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln74_fu_443_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_1_fu_454_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_2_fu_465_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_3_fu_476_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_4_fu_487_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_5_fu_498_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_6_fu_509_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_7_fu_520_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_8_fu_531_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_9_fu_542_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1303_fu_567_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_fu_567_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_fu_579_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1303_fu_573_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_61_fu_587_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_fu_607_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_1_fu_625_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_1_fu_625_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_2_fu_631_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_64_fu_637_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_2_fu_657_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_2_fu_675_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_2_fu_675_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_4_fu_681_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal grp_fu_332_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_67_fu_687_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_68_fu_697_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_4_fu_707_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_5_fu_715_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_3_fu_733_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_3_fu_733_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_6_fu_739_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_70_fu_745_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_6_fu_765_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_4_fu_783_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_4_fu_783_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_8_fu_789_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_73_fu_795_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_8_fu_815_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_5_fu_833_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_5_fu_833_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_10_fu_839_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_76_fu_845_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_10_fu_865_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_6_fu_883_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_6_fu_883_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_12_fu_889_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_79_fu_895_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_12_fu_915_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_7_fu_933_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_7_fu_933_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_14_fu_939_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_82_fu_945_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_83_fu_955_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_14_fu_965_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_15_fu_973_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_8_fu_991_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_8_fu_991_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_16_fu_997_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_85_fu_1003_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_16_fu_1023_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_9_fu_1041_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_9_fu_1041_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_18_fu_1047_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_88_fu_1053_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_18_fu_1073_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_10_fu_1091_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_10_fu_1091_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_20_fu_1097_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_91_fu_1103_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_20_fu_1123_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal add_ln74_10_fu_1137_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_11_fu_1147_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_12_fu_1157_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_13_fu_1167_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_14_fu_1177_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_15_fu_1187_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_16_fu_1197_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_17_fu_1207_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_18_fu_1217_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln74_19_fu_1227_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1303_1_fu_1237_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_3_fu_1246_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_7_fu_1258_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_9_fu_1267_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_11_fu_1276_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_13_fu_1285_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_17_fu_1297_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_19_fu_1306_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_11_fu_1319_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_11_fu_1319_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_22_fu_1325_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_94_fu_1331_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_22_fu_1351_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_12_fu_1369_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_12_fu_1369_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_24_fu_1375_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_97_fu_1381_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_98_fu_1391_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_24_fu_1401_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal sub_ln1303_25_fu_1409_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_13_fu_1427_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_13_fu_1427_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_26_fu_1433_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_100_fu_1439_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_26_fu_1459_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_14_fu_1477_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_14_fu_1477_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_28_fu_1483_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_103_fu_1489_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_28_fu_1509_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_15_fu_1527_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_15_fu_1527_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_30_fu_1533_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_106_fu_1539_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_30_fu_1559_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_16_fu_1577_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_16_fu_1577_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_32_fu_1583_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_109_fu_1589_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_32_fu_1609_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_17_fu_1627_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_17_fu_1627_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_34_fu_1633_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_112_fu_1639_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_34_fu_1659_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_18_fu_1677_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_18_fu_1677_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_36_fu_1683_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_115_fu_1689_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_36_fu_1709_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_19_fu_1727_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_19_fu_1727_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_38_fu_1733_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_118_fu_1739_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_38_fu_1759_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln1303_20_fu_1777_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal mul_ln1303_20_fu_1777_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln1303_40_fu_1783_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_121_fu_1789_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_40_fu_1809_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln74_1_fu_1251_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_fu_1242_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_fu_1823_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_3_fu_1263_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_4_fu_1272_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_21_fu_1833_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln813_2_fu_1839_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_2_fu_1255_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_22_fu_1843_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_1_fu_1829_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_23_fu_1849_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_5_fu_1281_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_6_fu_1290_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_24_fu_1859_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_8_fu_1302_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_9_fu_1311_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_25_fu_1869_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln813_5_fu_1875_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_7_fu_1294_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_26_fu_1879_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_4_fu_1865_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_27_fu_1885_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_6_fu_1891_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_3_fu_1855_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln1303_21_fu_1905_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_23_fu_1914_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_27_fu_1926_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_29_fu_1935_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_31_fu_1944_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_33_fu_1953_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_35_fu_1962_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_37_fu_1971_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_39_fu_1980_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln1303_41_fu_1989_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln74_10_fu_1910_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_11_fu_1919_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_29_fu_2001_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_13_fu_1931_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_14_fu_1940_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_30_fu_2011_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln813_9_fu_2017_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_12_fu_1923_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_32_fu_2021_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_8_fu_2007_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_33_fu_2027_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_16_fu_1958_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln74_17_fu_1967_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_34_fu_2037_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln813_11_fu_2043_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_15_fu_1949_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_35_fu_2047_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_19_fu_1985_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln813_fu_1994_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln813_36_fu_2057_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln813_13_fu_2063_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln74_18_fu_1976_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln813_37_fu_2067_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln813_14_fu_2073_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_12_fu_2053_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln813_38_fu_2077_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln813_15_fu_2083_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln813_10_fu_2033_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_39_fu_2087_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln813_7_fu_1998_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component CNN_mul_32s_34ns_65_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (33 downto 0);
        dout : OUT STD_LOGIC_VECTOR (64 downto 0) );
    end component;


    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_34ns_65_1_1_U111 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q10,
        din1 => mul_ln1303_fu_567_p1,
        dout => mul_ln1303_fu_567_p2);

    mul_32s_34ns_65_1_1_U112 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q9,
        din1 => mul_ln1303_1_fu_625_p1,
        dout => mul_ln1303_1_fu_625_p2);

    mul_32s_34ns_65_1_1_U113 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q8,
        din1 => mul_ln1303_2_fu_675_p1,
        dout => mul_ln1303_2_fu_675_p2);

    mul_32s_34ns_65_1_1_U114 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q7,
        din1 => mul_ln1303_3_fu_733_p1,
        dout => mul_ln1303_3_fu_733_p2);

    mul_32s_34ns_65_1_1_U115 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q6,
        din1 => mul_ln1303_4_fu_783_p1,
        dout => mul_ln1303_4_fu_783_p2);

    mul_32s_34ns_65_1_1_U116 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q5,
        din1 => mul_ln1303_5_fu_833_p1,
        dout => mul_ln1303_5_fu_833_p2);

    mul_32s_34ns_65_1_1_U117 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q4,
        din1 => mul_ln1303_6_fu_883_p1,
        dout => mul_ln1303_6_fu_883_p2);

    mul_32s_34ns_65_1_1_U118 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q3,
        din1 => mul_ln1303_7_fu_933_p1,
        dout => mul_ln1303_7_fu_933_p2);

    mul_32s_34ns_65_1_1_U119 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q2,
        din1 => mul_ln1303_8_fu_991_p1,
        dout => mul_ln1303_8_fu_991_p2);

    mul_32s_34ns_65_1_1_U120 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q1,
        din1 => mul_ln1303_9_fu_1041_p1,
        dout => mul_ln1303_9_fu_1041_p2);

    mul_32s_34ns_65_1_1_U121 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q0,
        din1 => mul_ln1303_10_fu_1091_p1,
        dout => mul_ln1303_10_fu_1091_p2);

    mul_32s_34ns_65_1_1_U122 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q9,
        din1 => mul_ln1303_11_fu_1319_p1,
        dout => mul_ln1303_11_fu_1319_p2);

    mul_32s_34ns_65_1_1_U123 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q8,
        din1 => mul_ln1303_12_fu_1369_p1,
        dout => mul_ln1303_12_fu_1369_p2);

    mul_32s_34ns_65_1_1_U124 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q7,
        din1 => mul_ln1303_13_fu_1427_p1,
        dout => mul_ln1303_13_fu_1427_p2);

    mul_32s_34ns_65_1_1_U125 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q6,
        din1 => mul_ln1303_14_fu_1477_p1,
        dout => mul_ln1303_14_fu_1477_p2);

    mul_32s_34ns_65_1_1_U126 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q5,
        din1 => mul_ln1303_15_fu_1527_p1,
        dout => mul_ln1303_15_fu_1527_p2);

    mul_32s_34ns_65_1_1_U127 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q4,
        din1 => mul_ln1303_16_fu_1577_p1,
        dout => mul_ln1303_16_fu_1577_p2);

    mul_32s_34ns_65_1_1_U128 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q3,
        din1 => mul_ln1303_17_fu_1627_p1,
        dout => mul_ln1303_17_fu_1627_p2);

    mul_32s_34ns_65_1_1_U129 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q2,
        din1 => mul_ln1303_18_fu_1677_p1,
        dout => mul_ln1303_18_fu_1677_p2);

    mul_32s_34ns_65_1_1_U130 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q1,
        din1 => mul_ln1303_19_fu_1727_p1,
        dout => mul_ln1303_19_fu_1727_p2);

    mul_32s_34ns_65_1_1_U131 : component CNN_mul_32s_34ns_65_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 34,
        dout_WIDTH => 65)
    port map (
        din0 => batch_normalization_8_V_q0,
        din1 => mul_ln1303_20_fu_1777_p1,
        dout => mul_ln1303_20_fu_1777_p2);

    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    hs_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln71_fu_417_p2 = ap_const_lv1_0))) then 
                    hs_fu_94 <= add_ln71_fu_423_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    hs_fu_94 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln71_fu_417_p2 = ap_const_lv1_0))) then 
                    phi_mul_fu_90 <= next_mul_fu_432_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_90 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln813_28_reg_2527 <= add_ln813_28_fu_1895_p2;
                i_reg_2114 <= ap_sig_allocacmp_i;
                i_reg_2114_pp0_iter1_reg <= i_reg_2114;
                icmp_ln71_reg_2119 <= icmp_ln71_fu_417_p2;
                select_ln1303_25_reg_2402 <= select_ln1303_25_fu_1415_p3;
                sub_ln1303_23_reg_2397 <= sub_ln1303_23_fu_1359_p2;
                sub_ln1303_27_reg_2417 <= sub_ln1303_27_fu_1467_p2;
                sub_ln1303_29_reg_2432 <= sub_ln1303_29_fu_1517_p2;
                sub_ln1303_31_reg_2447 <= sub_ln1303_31_fu_1567_p2;
                sub_ln1303_33_reg_2462 <= sub_ln1303_33_fu_1617_p2;
                sub_ln1303_35_reg_2477 <= sub_ln1303_35_fu_1667_p2;
                sub_ln1303_37_reg_2492 <= sub_ln1303_37_fu_1717_p2;
                sub_ln1303_39_reg_2507 <= sub_ln1303_39_fu_1767_p2;
                sub_ln1303_41_reg_2522 <= sub_ln1303_41_fu_1817_p2;
                tmp_101_reg_2412 <= mul_ln1303_13_fu_1427_p2(64 downto 37);
                tmp_104_reg_2427 <= mul_ln1303_14_fu_1477_p2(64 downto 37);
                tmp_107_reg_2442 <= mul_ln1303_15_fu_1527_p2(64 downto 37);
                tmp_110_reg_2457 <= mul_ln1303_16_fu_1577_p2(64 downto 37);
                tmp_113_reg_2472 <= mul_ln1303_17_fu_1627_p2(64 downto 37);
                tmp_116_reg_2487 <= mul_ln1303_18_fu_1677_p2(64 downto 37);
                tmp_119_reg_2502 <= mul_ln1303_19_fu_1727_p2(64 downto 37);
                tmp_122_reg_2517 <= mul_ln1303_20_fu_1777_p2(64 downto 37);
                tmp_95_reg_2392 <= mul_ln1303_11_fu_1319_p2(64 downto 37);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln71_fu_417_p2 = ap_const_lv1_0))) then
                phi_mul_load_reg_2123 <= ap_sig_allocacmp_phi_mul_load;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_reg_2119 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                select_ln1303_15_reg_2287 <= select_ln1303_15_fu_979_p3;
                select_ln1303_5_reg_2222 <= select_ln1303_5_fu_721_p3;
                sub_ln1303_11_reg_2267 <= sub_ln1303_11_fu_873_p2;
                sub_ln1303_13_reg_2282 <= sub_ln1303_13_fu_923_p2;
                sub_ln1303_17_reg_2302 <= sub_ln1303_17_fu_1031_p2;
                sub_ln1303_19_reg_2317 <= sub_ln1303_19_fu_1081_p2;
                sub_ln1303_1_reg_2202 <= sub_ln1303_1_fu_615_p2;
                sub_ln1303_21_reg_2332 <= sub_ln1303_21_fu_1131_p2;
                sub_ln1303_3_reg_2217 <= sub_ln1303_3_fu_665_p2;
                sub_ln1303_7_reg_2237 <= sub_ln1303_7_fu_773_p2;
                sub_ln1303_9_reg_2252 <= sub_ln1303_9_fu_823_p2;
                tmp_62_reg_2197 <= mul_ln1303_fu_567_p2(64 downto 37);
                tmp_65_reg_2212 <= mul_ln1303_1_fu_625_p2(64 downto 37);
                tmp_71_reg_2232 <= mul_ln1303_3_fu_733_p2(64 downto 37);
                tmp_74_reg_2247 <= mul_ln1303_4_fu_783_p2(64 downto 37);
                tmp_77_reg_2262 <= mul_ln1303_5_fu_833_p2(64 downto 37);
                tmp_80_reg_2277 <= mul_ln1303_6_fu_883_p2(64 downto 37);
                tmp_86_reg_2297 <= mul_ln1303_8_fu_991_p2(64 downto 37);
                tmp_89_reg_2312 <= mul_ln1303_9_fu_1041_p2(64 downto 37);
                tmp_92_reg_2327 <= mul_ln1303_10_fu_1091_p2(64 downto 37);
                tmp_reg_2192 <= tmp_fu_579_p1(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_102_reg_2422 <= grp_fu_348_p1(31 downto 31);
                tmp_105_reg_2437 <= grp_fu_356_p1(31 downto 31);
                tmp_108_reg_2452 <= grp_fu_364_p1(31 downto 31);
                tmp_111_reg_2467 <= grp_fu_372_p1(31 downto 31);
                tmp_114_reg_2482 <= grp_fu_380_p1(31 downto 31);
                tmp_117_reg_2497 <= grp_fu_388_p1(31 downto 31);
                tmp_120_reg_2512 <= grp_fu_396_p1(31 downto 31);
                tmp_93_reg_2387 <= grp_fu_324_p1(31 downto 31);
                tmp_99_reg_2407 <= grp_fu_340_p1(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_reg_2119 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                tmp_63_reg_2207 <= grp_fu_324_p1(31 downto 31);
                tmp_69_reg_2227 <= grp_fu_340_p1(31 downto 31);
                tmp_72_reg_2242 <= grp_fu_348_p1(31 downto 31);
                tmp_75_reg_2257 <= grp_fu_356_p1(31 downto 31);
                tmp_78_reg_2272 <= grp_fu_364_p1(31 downto 31);
                tmp_84_reg_2292 <= grp_fu_380_p1(31 downto 31);
                tmp_87_reg_2307 <= grp_fu_388_p1(31 downto 31);
                tmp_90_reg_2322 <= grp_fu_396_p1(31 downto 31);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln71_fu_423_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv4_1));
    add_ln74_10_fu_1137_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_B));
    add_ln74_11_fu_1147_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_C));
    add_ln74_12_fu_1157_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_D));
    add_ln74_13_fu_1167_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_E));
    add_ln74_14_fu_1177_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_F));
    add_ln74_15_fu_1187_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_10));
    add_ln74_16_fu_1197_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_11));
    add_ln74_17_fu_1207_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_12));
    add_ln74_18_fu_1217_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_13));
    add_ln74_19_fu_1227_p2 <= std_logic_vector(unsigned(phi_mul_load_reg_2123) + unsigned(ap_const_lv8_14));
    add_ln74_1_fu_454_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_2));
    add_ln74_2_fu_465_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_3));
    add_ln74_3_fu_476_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_4));
    add_ln74_4_fu_487_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_5));
    add_ln74_5_fu_498_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_6));
    add_ln74_6_fu_509_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_7));
    add_ln74_7_fu_520_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_8));
    add_ln74_8_fu_531_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_9));
    add_ln74_9_fu_542_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_A));
    add_ln74_fu_443_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_1));
    add_ln813_21_fu_1833_p2 <= std_logic_vector(signed(sext_ln74_3_fu_1263_p1) + signed(sext_ln74_4_fu_1272_p1));
    add_ln813_22_fu_1843_p2 <= std_logic_vector(signed(sext_ln813_2_fu_1839_p1) + signed(sext_ln74_2_fu_1255_p1));
    add_ln813_23_fu_1849_p2 <= std_logic_vector(unsigned(add_ln813_22_fu_1843_p2) + unsigned(sext_ln813_1_fu_1829_p1));
    add_ln813_24_fu_1859_p2 <= std_logic_vector(signed(sext_ln74_5_fu_1281_p1) + signed(sext_ln74_6_fu_1290_p1));
    add_ln813_25_fu_1869_p2 <= std_logic_vector(signed(sext_ln74_8_fu_1302_p1) + signed(sext_ln74_9_fu_1311_p1));
    add_ln813_26_fu_1879_p2 <= std_logic_vector(signed(sext_ln813_5_fu_1875_p1) + signed(sext_ln74_7_fu_1294_p1));
    add_ln813_27_fu_1885_p2 <= std_logic_vector(unsigned(add_ln813_26_fu_1879_p2) + unsigned(sext_ln813_4_fu_1865_p1));
    add_ln813_28_fu_1895_p2 <= std_logic_vector(signed(sext_ln813_6_fu_1891_p1) + signed(sext_ln813_3_fu_1855_p1));
    add_ln813_29_fu_2001_p2 <= std_logic_vector(signed(sext_ln74_10_fu_1910_p1) + signed(sext_ln74_11_fu_1919_p1));
    add_ln813_30_fu_2011_p2 <= std_logic_vector(signed(sext_ln74_13_fu_1931_p1) + signed(sext_ln74_14_fu_1940_p1));
    add_ln813_32_fu_2021_p2 <= std_logic_vector(signed(sext_ln813_9_fu_2017_p1) + signed(sext_ln74_12_fu_1923_p1));
    add_ln813_33_fu_2027_p2 <= std_logic_vector(unsigned(add_ln813_32_fu_2021_p2) + unsigned(sext_ln813_8_fu_2007_p1));
    add_ln813_34_fu_2037_p2 <= std_logic_vector(signed(sext_ln74_16_fu_1958_p1) + signed(sext_ln74_17_fu_1967_p1));
    add_ln813_35_fu_2047_p2 <= std_logic_vector(signed(sext_ln813_11_fu_2043_p1) + signed(sext_ln74_15_fu_1949_p1));
    add_ln813_36_fu_2057_p2 <= std_logic_vector(signed(sext_ln74_19_fu_1985_p1) + signed(sext_ln813_fu_1994_p1));
    add_ln813_37_fu_2067_p2 <= std_logic_vector(signed(sext_ln813_13_fu_2063_p1) + signed(sext_ln74_18_fu_1976_p1));
    add_ln813_38_fu_2077_p2 <= std_logic_vector(signed(sext_ln813_14_fu_2073_p1) + signed(sext_ln813_12_fu_2053_p1));
    add_ln813_39_fu_2087_p2 <= std_logic_vector(signed(sext_ln813_15_fu_2083_p1) + signed(sext_ln813_10_fu_2033_p1));
    add_ln813_fu_1823_p2 <= std_logic_vector(signed(sext_ln74_1_fu_1251_p1) + signed(sext_ln74_fu_1242_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln71_reg_2119)
    begin
        if (((icmp_ln71_reg_2119 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, hs_fu_94)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i <= hs_fu_94;
        end if; 
    end process;


    ap_sig_allocacmp_phi_mul_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, phi_mul_fu_90, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_phi_mul_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_phi_mul_load <= phi_mul_fu_90;
        end if; 
    end process;


    batch_normalization_8_V_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_10_fu_548_p1, ap_block_pp0_stage1, zext_ln74_20_fu_1232_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address0 <= zext_ln74_20_fu_1232_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address0 <= zext_ln74_10_fu_548_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address0 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_9_fu_537_p1, ap_block_pp0_stage1, zext_ln74_19_fu_1222_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address1 <= zext_ln74_19_fu_1222_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address1 <= zext_ln74_9_fu_537_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address1 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address1 <= "XXXXXXXX";
        end if; 
    end process;

    batch_normalization_8_V_address10 <= zext_ln74_fu_438_p1(8 - 1 downto 0);

    batch_normalization_8_V_address2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_8_fu_526_p1, ap_block_pp0_stage1, zext_ln74_18_fu_1212_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address2 <= zext_ln74_18_fu_1212_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address2 <= zext_ln74_8_fu_526_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address2 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address2 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_7_fu_515_p1, ap_block_pp0_stage1, zext_ln74_17_fu_1202_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address3 <= zext_ln74_17_fu_1202_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address3 <= zext_ln74_7_fu_515_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address3 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address3 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_6_fu_504_p1, ap_block_pp0_stage1, zext_ln74_16_fu_1192_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address4 <= zext_ln74_16_fu_1192_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address4 <= zext_ln74_6_fu_504_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address4 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address4 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_5_fu_493_p1, ap_block_pp0_stage1, zext_ln74_15_fu_1182_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address5 <= zext_ln74_15_fu_1182_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address5 <= zext_ln74_5_fu_493_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address5 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address5 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_4_fu_482_p1, ap_block_pp0_stage1, zext_ln74_14_fu_1172_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address6 <= zext_ln74_14_fu_1172_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address6 <= zext_ln74_4_fu_482_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address6 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address6 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_3_fu_471_p1, ap_block_pp0_stage1, zext_ln74_13_fu_1162_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address7 <= zext_ln74_13_fu_1162_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address7 <= zext_ln74_3_fu_471_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address7 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address7 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_2_fu_460_p1, ap_block_pp0_stage1, zext_ln74_12_fu_1152_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address8 <= zext_ln74_12_fu_1152_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address8 <= zext_ln74_2_fu_460_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address8 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address8 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_address9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln74_1_fu_449_p1, zext_ln74_11_fu_1142_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                batch_normalization_8_V_address9 <= zext_ln74_11_fu_1142_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                batch_normalization_8_V_address9 <= zext_ln74_1_fu_449_p1(8 - 1 downto 0);
            else 
                batch_normalization_8_V_address9 <= "XXXXXXXX";
            end if;
        else 
            batch_normalization_8_V_address9 <= "XXXXXXXX";
        end if; 
    end process;


    batch_normalization_8_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce0 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce1 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce10_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            batch_normalization_8_V_ce10 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce10 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce2 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce3 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce4 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce5 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce6 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce7 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce8 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce8 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_8_V_ce9_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            batch_normalization_8_V_ce9 <= ap_const_logic_1;
        else 
            batch_normalization_8_V_ce9 <= ap_const_logic_0;
        end if; 
    end process;

    global_average_pooling1d_1_V_address0 <= i_6_cast106_fu_1901_p1(4 - 1 downto 0);

    global_average_pooling1d_1_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            global_average_pooling1d_1_V_ce0 <= ap_const_logic_1;
        else 
            global_average_pooling1d_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    global_average_pooling1d_1_V_d0 <= std_logic_vector(unsigned(add_ln813_39_fu_2087_p2) + unsigned(sext_ln813_7_fu_1998_p1));

    global_average_pooling1d_1_V_we0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            global_average_pooling1d_1_V_we0 <= ap_const_logic_1;
        else 
            global_average_pooling1d_1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_324_p1 <= batch_normalization_8_V_q9;
    grp_fu_324_p3 <= grp_fu_324_p1(31 downto 31);
    grp_fu_332_p1 <= batch_normalization_8_V_q8;
    grp_fu_332_p3 <= grp_fu_332_p1(31 downto 31);
    grp_fu_340_p1 <= batch_normalization_8_V_q7;
    grp_fu_340_p3 <= grp_fu_340_p1(31 downto 31);
    grp_fu_348_p1 <= batch_normalization_8_V_q6;
    grp_fu_348_p3 <= grp_fu_348_p1(31 downto 31);
    grp_fu_356_p1 <= batch_normalization_8_V_q5;
    grp_fu_356_p3 <= grp_fu_356_p1(31 downto 31);
    grp_fu_364_p1 <= batch_normalization_8_V_q4;
    grp_fu_364_p3 <= grp_fu_364_p1(31 downto 31);
    grp_fu_372_p1 <= batch_normalization_8_V_q3;
    grp_fu_372_p3 <= grp_fu_372_p1(31 downto 31);
    grp_fu_380_p1 <= batch_normalization_8_V_q2;
    grp_fu_380_p3 <= grp_fu_380_p1(31 downto 31);
    grp_fu_388_p1 <= batch_normalization_8_V_q1;
    grp_fu_388_p3 <= grp_fu_388_p1(31 downto 31);
    grp_fu_396_p1 <= batch_normalization_8_V_q0;
    grp_fu_396_p3 <= grp_fu_396_p1(31 downto 31);
    i_6_cast106_fu_1901_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_2114_pp0_iter1_reg),64));
    icmp_ln71_fu_417_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv4_B) else "0";
    mul_ln1303_10_fu_1091_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_11_fu_1319_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_12_fu_1369_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_13_fu_1427_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_14_fu_1477_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_15_fu_1527_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_16_fu_1577_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_17_fu_1627_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_18_fu_1677_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_19_fu_1727_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_1_fu_625_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_20_fu_1777_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_2_fu_675_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_3_fu_733_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_4_fu_783_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_5_fu_833_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_6_fu_883_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_7_fu_933_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_8_fu_991_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_9_fu_1041_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    mul_ln1303_fu_567_p1 <= ap_const_lv65_186186187(34 - 1 downto 0);
    next_mul_fu_432_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_15));
    select_ln1303_10_fu_865_p3 <= 
        tmp_76_fu_845_p4 when (grp_fu_356_p3(0) = '1') else 
        tmp_77_fu_855_p4;
    select_ln1303_11_fu_1276_p3 <= 
        sub_ln1303_11_reg_2267 when (tmp_75_reg_2257(0) = '1') else 
        tmp_77_reg_2262;
    select_ln1303_12_fu_915_p3 <= 
        tmp_79_fu_895_p4 when (grp_fu_364_p3(0) = '1') else 
        tmp_80_fu_905_p4;
    select_ln1303_13_fu_1285_p3 <= 
        sub_ln1303_13_reg_2282 when (tmp_78_reg_2272(0) = '1') else 
        tmp_80_reg_2277;
    select_ln1303_14_fu_965_p3 <= 
        tmp_82_fu_945_p4 when (grp_fu_372_p3(0) = '1') else 
        tmp_83_fu_955_p4;
    select_ln1303_15_fu_979_p3 <= 
        sub_ln1303_15_fu_973_p2 when (grp_fu_372_p3(0) = '1') else 
        tmp_83_fu_955_p4;
    select_ln1303_16_fu_1023_p3 <= 
        tmp_85_fu_1003_p4 when (grp_fu_380_p3(0) = '1') else 
        tmp_86_fu_1013_p4;
    select_ln1303_17_fu_1297_p3 <= 
        sub_ln1303_17_reg_2302 when (tmp_84_reg_2292(0) = '1') else 
        tmp_86_reg_2297;
    select_ln1303_18_fu_1073_p3 <= 
        tmp_88_fu_1053_p4 when (grp_fu_388_p3(0) = '1') else 
        tmp_89_fu_1063_p4;
    select_ln1303_19_fu_1306_p3 <= 
        sub_ln1303_19_reg_2317 when (tmp_87_reg_2307(0) = '1') else 
        tmp_89_reg_2312;
    select_ln1303_1_fu_1237_p3 <= 
        sub_ln1303_1_reg_2202 when (tmp_reg_2192(0) = '1') else 
        tmp_62_reg_2197;
    select_ln1303_20_fu_1123_p3 <= 
        tmp_91_fu_1103_p4 when (grp_fu_396_p3(0) = '1') else 
        tmp_92_fu_1113_p4;
    select_ln1303_21_fu_1905_p3 <= 
        sub_ln1303_21_reg_2332 when (tmp_90_reg_2322(0) = '1') else 
        tmp_92_reg_2327;
    select_ln1303_22_fu_1351_p3 <= 
        tmp_94_fu_1331_p4 when (grp_fu_324_p3(0) = '1') else 
        tmp_95_fu_1341_p4;
    select_ln1303_23_fu_1914_p3 <= 
        sub_ln1303_23_reg_2397 when (tmp_93_reg_2387(0) = '1') else 
        tmp_95_reg_2392;
    select_ln1303_24_fu_1401_p3 <= 
        tmp_97_fu_1381_p4 when (grp_fu_332_p3(0) = '1') else 
        tmp_98_fu_1391_p4;
    select_ln1303_25_fu_1415_p3 <= 
        sub_ln1303_25_fu_1409_p2 when (grp_fu_332_p3(0) = '1') else 
        tmp_98_fu_1391_p4;
    select_ln1303_26_fu_1459_p3 <= 
        tmp_100_fu_1439_p4 when (grp_fu_340_p3(0) = '1') else 
        tmp_101_fu_1449_p4;
    select_ln1303_27_fu_1926_p3 <= 
        sub_ln1303_27_reg_2417 when (tmp_99_reg_2407(0) = '1') else 
        tmp_101_reg_2412;
    select_ln1303_28_fu_1509_p3 <= 
        tmp_103_fu_1489_p4 when (grp_fu_348_p3(0) = '1') else 
        tmp_104_fu_1499_p4;
    select_ln1303_29_fu_1935_p3 <= 
        sub_ln1303_29_reg_2432 when (tmp_102_reg_2422(0) = '1') else 
        tmp_104_reg_2427;
    select_ln1303_2_fu_657_p3 <= 
        tmp_64_fu_637_p4 when (grp_fu_324_p3(0) = '1') else 
        tmp_65_fu_647_p4;
    select_ln1303_30_fu_1559_p3 <= 
        tmp_106_fu_1539_p4 when (grp_fu_356_p3(0) = '1') else 
        tmp_107_fu_1549_p4;
    select_ln1303_31_fu_1944_p3 <= 
        sub_ln1303_31_reg_2447 when (tmp_105_reg_2437(0) = '1') else 
        tmp_107_reg_2442;
    select_ln1303_32_fu_1609_p3 <= 
        tmp_109_fu_1589_p4 when (grp_fu_364_p3(0) = '1') else 
        tmp_110_fu_1599_p4;
    select_ln1303_33_fu_1953_p3 <= 
        sub_ln1303_33_reg_2462 when (tmp_108_reg_2452(0) = '1') else 
        tmp_110_reg_2457;
    select_ln1303_34_fu_1659_p3 <= 
        tmp_112_fu_1639_p4 when (grp_fu_372_p3(0) = '1') else 
        tmp_113_fu_1649_p4;
    select_ln1303_35_fu_1962_p3 <= 
        sub_ln1303_35_reg_2477 when (tmp_111_reg_2467(0) = '1') else 
        tmp_113_reg_2472;
    select_ln1303_36_fu_1709_p3 <= 
        tmp_115_fu_1689_p4 when (grp_fu_380_p3(0) = '1') else 
        tmp_116_fu_1699_p4;
    select_ln1303_37_fu_1971_p3 <= 
        sub_ln1303_37_reg_2492 when (tmp_114_reg_2482(0) = '1') else 
        tmp_116_reg_2487;
    select_ln1303_38_fu_1759_p3 <= 
        tmp_118_fu_1739_p4 when (grp_fu_388_p3(0) = '1') else 
        tmp_119_fu_1749_p4;
    select_ln1303_39_fu_1980_p3 <= 
        sub_ln1303_39_reg_2507 when (tmp_117_reg_2497(0) = '1') else 
        tmp_119_reg_2502;
    select_ln1303_3_fu_1246_p3 <= 
        sub_ln1303_3_reg_2217 when (tmp_63_reg_2207(0) = '1') else 
        tmp_65_reg_2212;
    select_ln1303_40_fu_1809_p3 <= 
        tmp_121_fu_1789_p4 when (grp_fu_396_p3(0) = '1') else 
        tmp_122_fu_1799_p4;
    select_ln1303_41_fu_1989_p3 <= 
        sub_ln1303_41_reg_2522 when (tmp_120_reg_2512(0) = '1') else 
        tmp_122_reg_2517;
    select_ln1303_4_fu_707_p3 <= 
        tmp_67_fu_687_p4 when (grp_fu_332_p3(0) = '1') else 
        tmp_68_fu_697_p4;
    select_ln1303_5_fu_721_p3 <= 
        sub_ln1303_5_fu_715_p2 when (grp_fu_332_p3(0) = '1') else 
        tmp_68_fu_697_p4;
    select_ln1303_6_fu_765_p3 <= 
        tmp_70_fu_745_p4 when (grp_fu_340_p3(0) = '1') else 
        tmp_71_fu_755_p4;
    select_ln1303_7_fu_1258_p3 <= 
        sub_ln1303_7_reg_2237 when (tmp_69_reg_2227(0) = '1') else 
        tmp_71_reg_2232;
    select_ln1303_8_fu_815_p3 <= 
        tmp_73_fu_795_p4 when (grp_fu_348_p3(0) = '1') else 
        tmp_74_fu_805_p4;
    select_ln1303_9_fu_1267_p3 <= 
        sub_ln1303_9_reg_2252 when (tmp_72_reg_2242(0) = '1') else 
        tmp_74_reg_2247;
    select_ln1303_fu_607_p3 <= 
        tmp_61_fu_587_p4 when (tmp_fu_579_p3(0) = '1') else 
        tmp_62_fu_597_p4;
        sext_ln74_10_fu_1910_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_21_fu_1905_p3),29));

        sext_ln74_11_fu_1919_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_23_fu_1914_p3),29));

        sext_ln74_12_fu_1923_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_25_reg_2402),30));

        sext_ln74_13_fu_1931_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_27_fu_1926_p3),29));

        sext_ln74_14_fu_1940_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_29_fu_1935_p3),29));

        sext_ln74_15_fu_1949_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_31_fu_1944_p3),30));

        sext_ln74_16_fu_1958_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_33_fu_1953_p3),29));

        sext_ln74_17_fu_1967_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_35_fu_1962_p3),29));

        sext_ln74_18_fu_1976_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_37_fu_1971_p3),30));

        sext_ln74_19_fu_1985_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_39_fu_1980_p3),29));

        sext_ln74_1_fu_1251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_3_fu_1246_p3),29));

        sext_ln74_2_fu_1255_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_5_reg_2222),30));

        sext_ln74_3_fu_1263_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_7_fu_1258_p3),29));

        sext_ln74_4_fu_1272_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_9_fu_1267_p3),29));

        sext_ln74_5_fu_1281_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_11_fu_1276_p3),29));

        sext_ln74_6_fu_1290_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_13_fu_1285_p3),29));

        sext_ln74_7_fu_1294_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_15_reg_2287),30));

        sext_ln74_8_fu_1302_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_17_fu_1297_p3),29));

        sext_ln74_9_fu_1311_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_19_fu_1306_p3),29));

        sext_ln74_fu_1242_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_1_fu_1237_p3),29));

        sext_ln813_10_fu_2033_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_33_fu_2027_p2),32));

        sext_ln813_11_fu_2043_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_34_fu_2037_p2),30));

        sext_ln813_12_fu_2053_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_35_fu_2047_p2),31));

        sext_ln813_13_fu_2063_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_36_fu_2057_p2),30));

        sext_ln813_14_fu_2073_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_37_fu_2067_p2),31));

        sext_ln813_15_fu_2083_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_38_fu_2077_p2),32));

        sext_ln813_1_fu_1829_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_fu_1823_p2),30));

        sext_ln813_2_fu_1839_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_21_fu_1833_p2),30));

        sext_ln813_3_fu_1855_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_23_fu_1849_p2),31));

        sext_ln813_4_fu_1865_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_24_fu_1859_p2),30));

        sext_ln813_5_fu_1875_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_25_fu_1869_p2),30));

        sext_ln813_6_fu_1891_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_27_fu_1885_p2),31));

        sext_ln813_7_fu_1998_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_28_reg_2527),32));

        sext_ln813_8_fu_2007_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_29_fu_2001_p2),30));

        sext_ln813_9_fu_2017_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_30_fu_2011_p2),30));

        sext_ln813_fu_1994_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1303_41_fu_1989_p3),29));

    sub_ln1303_10_fu_839_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_5_fu_833_p2));
    sub_ln1303_11_fu_873_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_10_fu_865_p3));
    sub_ln1303_12_fu_889_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_6_fu_883_p2));
    sub_ln1303_13_fu_923_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_12_fu_915_p3));
    sub_ln1303_14_fu_939_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_7_fu_933_p2));
    sub_ln1303_15_fu_973_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_14_fu_965_p3));
    sub_ln1303_16_fu_997_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_8_fu_991_p2));
    sub_ln1303_17_fu_1031_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_16_fu_1023_p3));
    sub_ln1303_18_fu_1047_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_9_fu_1041_p2));
    sub_ln1303_19_fu_1081_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_18_fu_1073_p3));
    sub_ln1303_1_fu_615_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_fu_607_p3));
    sub_ln1303_20_fu_1097_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_10_fu_1091_p2));
    sub_ln1303_21_fu_1131_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_20_fu_1123_p3));
    sub_ln1303_22_fu_1325_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_11_fu_1319_p2));
    sub_ln1303_23_fu_1359_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_22_fu_1351_p3));
    sub_ln1303_24_fu_1375_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_12_fu_1369_p2));
    sub_ln1303_25_fu_1409_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_24_fu_1401_p3));
    sub_ln1303_26_fu_1433_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_13_fu_1427_p2));
    sub_ln1303_27_fu_1467_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_26_fu_1459_p3));
    sub_ln1303_28_fu_1483_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_14_fu_1477_p2));
    sub_ln1303_29_fu_1517_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_28_fu_1509_p3));
    sub_ln1303_2_fu_631_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_1_fu_625_p2));
    sub_ln1303_30_fu_1533_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_15_fu_1527_p2));
    sub_ln1303_31_fu_1567_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_30_fu_1559_p3));
    sub_ln1303_32_fu_1583_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_16_fu_1577_p2));
    sub_ln1303_33_fu_1617_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_32_fu_1609_p3));
    sub_ln1303_34_fu_1633_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_17_fu_1627_p2));
    sub_ln1303_35_fu_1667_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_34_fu_1659_p3));
    sub_ln1303_36_fu_1683_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_18_fu_1677_p2));
    sub_ln1303_37_fu_1717_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_36_fu_1709_p3));
    sub_ln1303_38_fu_1733_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_19_fu_1727_p2));
    sub_ln1303_39_fu_1767_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_38_fu_1759_p3));
    sub_ln1303_3_fu_665_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_2_fu_657_p3));
    sub_ln1303_40_fu_1783_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_20_fu_1777_p2));
    sub_ln1303_41_fu_1817_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_40_fu_1809_p3));
    sub_ln1303_4_fu_681_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_2_fu_675_p2));
    sub_ln1303_5_fu_715_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_4_fu_707_p3));
    sub_ln1303_6_fu_739_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_3_fu_733_p2));
    sub_ln1303_7_fu_773_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_6_fu_765_p3));
    sub_ln1303_8_fu_789_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_4_fu_783_p2));
    sub_ln1303_9_fu_823_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(select_ln1303_8_fu_815_p3));
    sub_ln1303_fu_573_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln1303_fu_567_p2));
    tmp_100_fu_1439_p4 <= sub_ln1303_26_fu_1433_p2(64 downto 37);
    tmp_101_fu_1449_p4 <= mul_ln1303_13_fu_1427_p2(64 downto 37);
    tmp_103_fu_1489_p4 <= sub_ln1303_28_fu_1483_p2(64 downto 37);
    tmp_104_fu_1499_p4 <= mul_ln1303_14_fu_1477_p2(64 downto 37);
    tmp_106_fu_1539_p4 <= sub_ln1303_30_fu_1533_p2(64 downto 37);
    tmp_107_fu_1549_p4 <= mul_ln1303_15_fu_1527_p2(64 downto 37);
    tmp_109_fu_1589_p4 <= sub_ln1303_32_fu_1583_p2(64 downto 37);
    tmp_110_fu_1599_p4 <= mul_ln1303_16_fu_1577_p2(64 downto 37);
    tmp_112_fu_1639_p4 <= sub_ln1303_34_fu_1633_p2(64 downto 37);
    tmp_113_fu_1649_p4 <= mul_ln1303_17_fu_1627_p2(64 downto 37);
    tmp_115_fu_1689_p4 <= sub_ln1303_36_fu_1683_p2(64 downto 37);
    tmp_116_fu_1699_p4 <= mul_ln1303_18_fu_1677_p2(64 downto 37);
    tmp_118_fu_1739_p4 <= sub_ln1303_38_fu_1733_p2(64 downto 37);
    tmp_119_fu_1749_p4 <= mul_ln1303_19_fu_1727_p2(64 downto 37);
    tmp_121_fu_1789_p4 <= sub_ln1303_40_fu_1783_p2(64 downto 37);
    tmp_122_fu_1799_p4 <= mul_ln1303_20_fu_1777_p2(64 downto 37);
    tmp_61_fu_587_p4 <= sub_ln1303_fu_573_p2(64 downto 37);
    tmp_62_fu_597_p4 <= mul_ln1303_fu_567_p2(64 downto 37);
    tmp_64_fu_637_p4 <= sub_ln1303_2_fu_631_p2(64 downto 37);
    tmp_65_fu_647_p4 <= mul_ln1303_1_fu_625_p2(64 downto 37);
    tmp_67_fu_687_p4 <= sub_ln1303_4_fu_681_p2(64 downto 37);
    tmp_68_fu_697_p4 <= mul_ln1303_2_fu_675_p2(64 downto 37);
    tmp_70_fu_745_p4 <= sub_ln1303_6_fu_739_p2(64 downto 37);
    tmp_71_fu_755_p4 <= mul_ln1303_3_fu_733_p2(64 downto 37);
    tmp_73_fu_795_p4 <= sub_ln1303_8_fu_789_p2(64 downto 37);
    tmp_74_fu_805_p4 <= mul_ln1303_4_fu_783_p2(64 downto 37);
    tmp_76_fu_845_p4 <= sub_ln1303_10_fu_839_p2(64 downto 37);
    tmp_77_fu_855_p4 <= mul_ln1303_5_fu_833_p2(64 downto 37);
    tmp_79_fu_895_p4 <= sub_ln1303_12_fu_889_p2(64 downto 37);
    tmp_80_fu_905_p4 <= mul_ln1303_6_fu_883_p2(64 downto 37);
    tmp_82_fu_945_p4 <= sub_ln1303_14_fu_939_p2(64 downto 37);
    tmp_83_fu_955_p4 <= mul_ln1303_7_fu_933_p2(64 downto 37);
    tmp_85_fu_1003_p4 <= sub_ln1303_16_fu_997_p2(64 downto 37);
    tmp_86_fu_1013_p4 <= mul_ln1303_8_fu_991_p2(64 downto 37);
    tmp_88_fu_1053_p4 <= sub_ln1303_18_fu_1047_p2(64 downto 37);
    tmp_89_fu_1063_p4 <= mul_ln1303_9_fu_1041_p2(64 downto 37);
    tmp_91_fu_1103_p4 <= sub_ln1303_20_fu_1097_p2(64 downto 37);
    tmp_92_fu_1113_p4 <= mul_ln1303_10_fu_1091_p2(64 downto 37);
    tmp_94_fu_1331_p4 <= sub_ln1303_22_fu_1325_p2(64 downto 37);
    tmp_95_fu_1341_p4 <= mul_ln1303_11_fu_1319_p2(64 downto 37);
    tmp_97_fu_1381_p4 <= sub_ln1303_24_fu_1375_p2(64 downto 37);
    tmp_98_fu_1391_p4 <= mul_ln1303_12_fu_1369_p2(64 downto 37);
    tmp_fu_579_p1 <= batch_normalization_8_V_q10;
    tmp_fu_579_p3 <= tmp_fu_579_p1(31 downto 31);
    zext_ln74_10_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_9_fu_542_p2),64));
    zext_ln74_11_fu_1142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_10_fu_1137_p2),64));
    zext_ln74_12_fu_1152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_11_fu_1147_p2),64));
    zext_ln74_13_fu_1162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_12_fu_1157_p2),64));
    zext_ln74_14_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_13_fu_1167_p2),64));
    zext_ln74_15_fu_1182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_14_fu_1177_p2),64));
    zext_ln74_16_fu_1192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_15_fu_1187_p2),64));
    zext_ln74_17_fu_1202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_16_fu_1197_p2),64));
    zext_ln74_18_fu_1212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_17_fu_1207_p2),64));
    zext_ln74_19_fu_1222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_18_fu_1217_p2),64));
    zext_ln74_1_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_fu_443_p2),64));
    zext_ln74_20_fu_1232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_19_fu_1227_p2),64));
    zext_ln74_2_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_1_fu_454_p2),64));
    zext_ln74_3_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_2_fu_465_p2),64));
    zext_ln74_4_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_3_fu_476_p2),64));
    zext_ln74_5_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_4_fu_487_p2),64));
    zext_ln74_6_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_5_fu_498_p2),64));
    zext_ln74_7_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_6_fu_509_p2),64));
    zext_ln74_8_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_7_fu_520_p2),64));
    zext_ln74_9_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_8_fu_531_p2),64));
    zext_ln74_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_phi_mul_load),64));
end behav;
