-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CNN_CNN_Pipeline_loop_for_channel_pool_1_loop_for_weight_pool_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    batch_normalization_6_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    batch_normalization_6_V_ce0 : OUT STD_LOGIC;
    batch_normalization_6_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_normalization_6_V_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    batch_normalization_6_V_ce1 : OUT STD_LOGIC;
    batch_normalization_6_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    max_pooling1d_4_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    max_pooling1d_4_V_ce0 : OUT STD_LOGIC;
    max_pooling1d_4_V_we0 : OUT STD_LOGIC;
    max_pooling1d_4_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of CNN_CNN_Pipeline_loop_for_channel_pool_1_loop_for_weight_pool_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_AC0 : STD_LOGIC_VECTOR (11 downto 0) := "101011000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_FFF60000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111101100000000000000000";
    constant ap_const_lv13_56 : STD_LOGIC_VECTOR (12 downto 0) := "0000001010110";
    constant ap_const_lv12_2B : STD_LOGIC_VECTOR (11 downto 0) := "000000101011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln30_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln33_fu_146_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln33_reg_301 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln33_reg_301_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_268_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln41_reg_337 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln38_fu_211_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln38_1_fu_220_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_fu_254_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_fu_54 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln43_fu_176_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_y_load : STD_LOGIC_VECTOR (5 downto 0);
    signal z_fu_58 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln33_1_fu_160_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_z_load : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten144_fu_62 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln30_fu_128_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten144_load : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln33_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln30_1_fu_154_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_fu_200_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_258_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln37_fu_215_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln1649_18_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln39_fu_231_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1649_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_258_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_258_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_258_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_268_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_268_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_268_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_258_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_258_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_268_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_268_p20 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component CNN_mac_muladd_7ns_7ns_7ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component CNN_mac_muladd_7ns_6ns_6ns_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component CNN_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_7ns_7ns_7ns_13_4_1_U55 : component CNN_mac_muladd_7ns_7ns_7ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 7,
        din1_WIDTH => 7,
        din2_WIDTH => 7,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_258_p0,
        din1 => grp_fu_258_p1,
        din2 => grp_fu_258_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_258_p3);

    mac_muladd_7ns_6ns_6ns_12_4_1_U56 : component CNN_mac_muladd_7ns_6ns_6ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 7,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_268_p0,
        din1 => grp_fu_268_p1,
        din2 => grp_fu_268_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_268_p3);

    flow_control_loop_pipe_sequential_init_U : component CNN_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten144_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln30_fu_122_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten144_fu_62 <= add_ln30_fu_128_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten144_fu_62 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln30_fu_122_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    y_fu_54 <= add_ln43_fu_176_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_54 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    z_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln30_fu_122_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    z_fu_58 <= select_ln33_1_fu_160_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    z_fu_58 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                add_ln41_reg_337 <= grp_fu_268_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln33_reg_301_pp0_iter1_reg <= select_ln33_reg_301;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln30_fu_122_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln33_reg_301 <= select_ln33_fu_146_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln30_1_fu_154_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_z_load) + unsigned(ap_const_lv7_1));
    add_ln30_fu_128_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten144_load) + unsigned(ap_const_lv12_1));
    add_ln43_fu_176_p2 <= std_logic_vector(unsigned(select_ln33_fu_146_p3) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln30_fu_122_p2)
    begin
        if (((icmp_ln30_fu_122_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten144_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten144_fu_62)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten144_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten144_load <= indvar_flatten144_fu_62;
        end if; 
    end process;


    ap_sig_allocacmp_y_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, y_fu_54, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_y_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_y_load <= y_fu_54;
        end if; 
    end process;


    ap_sig_allocacmp_z_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, z_fu_58)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_z_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_z_load <= z_fu_58;
        end if; 
    end process;

    batch_normalization_6_V_address0 <= zext_ln38_1_fu_220_p1(13 - 1 downto 0);
    batch_normalization_6_V_address1 <= zext_ln38_fu_211_p1(13 - 1 downto 0);

    batch_normalization_6_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            batch_normalization_6_V_ce0 <= ap_const_logic_1;
        else 
            batch_normalization_6_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    batch_normalization_6_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            batch_normalization_6_V_ce1 <= ap_const_logic_1;
        else 
            batch_normalization_6_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_258_p0 <= grp_fu_258_p00(7 - 1 downto 0);
    grp_fu_258_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln33_1_fu_160_p3),13));
    grp_fu_258_p1 <= ap_const_lv13_56(7 - 1 downto 0);
    grp_fu_258_p2 <= grp_fu_258_p20(7 - 1 downto 0);
    grp_fu_258_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_200_p3),13));
    grp_fu_268_p0 <= grp_fu_268_p00(7 - 1 downto 0);
    grp_fu_268_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln33_1_fu_160_p3),12));
    grp_fu_268_p1 <= ap_const_lv12_2B(6 - 1 downto 0);
    grp_fu_268_p2 <= grp_fu_268_p20(6 - 1 downto 0);
    grp_fu_268_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln33_reg_301_pp0_iter1_reg),12));
    icmp_ln1649_18_fu_225_p2 <= "1" when (signed(batch_normalization_6_V_q1) > signed(ap_const_lv32_FFF60000)) else "0";
    icmp_ln1649_fu_239_p2 <= "1" when (signed(batch_normalization_6_V_q0) > signed(select_ln39_fu_231_p3)) else "0";
    icmp_ln30_fu_122_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten144_load = ap_const_lv12_AC0) else "0";
    icmp_ln33_fu_140_p2 <= "1" when (ap_sig_allocacmp_y_load = ap_const_lv6_2B) else "0";
    max_pooling1d_4_V_address0 <= zext_ln42_fu_254_p1(12 - 1 downto 0);

    max_pooling1d_4_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            max_pooling1d_4_V_ce0 <= ap_const_logic_1;
        else 
            max_pooling1d_4_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    max_pooling1d_4_V_d0 <= 
        batch_normalization_6_V_q0 when (icmp_ln1649_fu_239_p2(0) = '1') else 
        select_ln39_fu_231_p3;

    max_pooling1d_4_V_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            max_pooling1d_4_V_we0 <= ap_const_logic_1;
        else 
            max_pooling1d_4_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln37_fu_215_p2 <= (grp_fu_258_p3 or ap_const_lv13_1);
    select_ln33_1_fu_160_p3 <= 
        add_ln30_1_fu_154_p2 when (icmp_ln33_fu_140_p2(0) = '1') else 
        ap_sig_allocacmp_z_load;
    select_ln33_fu_146_p3 <= 
        ap_const_lv6_0 when (icmp_ln33_fu_140_p2(0) = '1') else 
        ap_sig_allocacmp_y_load;
    select_ln39_fu_231_p3 <= 
        batch_normalization_6_V_q1 when (icmp_ln1649_18_fu_225_p2(0) = '1') else 
        ap_const_lv32_FFF60000;
    tmp_s_fu_200_p3 <= (select_ln33_reg_301_pp0_iter1_reg & ap_const_lv1_0);
    zext_ln38_1_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln37_fu_215_p2),64));
    zext_ln38_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_258_p3),64));
    zext_ln42_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln41_reg_337),64));
end behav;
